import { Buffer } from 'node:buffer';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import type { CompiledMcpApp } from '../build/mcp-apps.ts';
import { MAX_APP_HTML_BYTES } from '../dev/mcp-apps/mcp-app-bridge.ts';
import {
  AGENT_BROWSER_TEST_REGISTRY_SYMBOL_KEY,
  AGENT_BROWSER_TEST_REGISTRY_VERSION,
  type AgentBrowserTestRegistry,
  type CompiledBrowserTestApp,
} from '../test/browser-registry.ts';
import { BROWSER_APP_PROOF_LEVEL, proofLevelLabel } from '../test/manifest.ts';

const compiledEntry = async (app: CompiledMcpApp): Promise<CompiledBrowserTestApp> => {
  const html = await readFile(app.output, 'utf8');
  const bytes = Buffer.byteLength(html, 'utf8');
  if (bytes > MAX_APP_HTML_BYTES) {
    throw new Error([
      `Compiled MCP App HTML exceeds the ${String(MAX_APP_HTML_BYTES)} byte browser harness bound.`,
      `  proof level: ${proofLevelLabel(BROWSER_APP_PROOF_LEVEL)}`,
      `  app:         ${app.name} (${app.resourceUri}, target ${app.target})`,
      `  output:      ${app.output}`,
      `  bytes:       ${String(bytes)}`,
    ].join('\n'));
  }
  return Object.freeze({
    html,
    name: app.name,
    output: app.output,
    proofLevel: BROWSER_APP_PROOF_LEVEL,
    resourceUri: app.resourceUri,
    serverIds: [...app.serverIds],
    target: app.target,
  });
};

export const browserTestSetupSource = (registry: AgentBrowserTestRegistry): string => [
  '// @generated by agent-bundle/rstest. Do not edit: rerun Rstest to regenerate.',
  `const registry = ${JSON.stringify(registry)};`,
  `globalThis[Symbol.for(${JSON.stringify(AGENT_BROWSER_TEST_REGISTRY_SYMBOL_KEY)})] = registry;`,
  '',
].join('\n');

export const writeBrowserTestSetup = async (
  projectRoot: string,
  compiled: readonly CompiledMcpApp[],
): Promise<string> => {
  const apps = Object.fromEntries(
    await Promise.all(compiled.map(async (app) => [app.name, await compiledEntry(app)] as const)),
  );
  const registry: AgentBrowserTestRegistry = Object.freeze({
    apps,
    version: AGENT_BROWSER_TEST_REGISTRY_VERSION,
  });
  const target = resolve(projectRoot, '.agent-bundle', 'test', 'browser-app-setup.mjs');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, browserTestSetupSource(registry), 'utf8');
  return target;
};
