import { Buffer } from 'node:buffer';
import { readFile } from 'node:fs/promises';

import type { CompiledMcpApp } from '../build/mcp-apps.ts';
import { MAX_APP_HTML_BYTES } from '../core/mcp-app-limits.ts';
import {
  AGENT_BROWSER_TEST_REGISTRY_SYMBOL_KEY,
  AGENT_BROWSER_TEST_REGISTRY_VERSION,
  type AgentBrowserTestRegistry,
  type CompiledBrowserTestApp,
} from '../test/browser-registry.ts';
import { BROWSER_APP_PROOF_LEVEL, proofLevelLabel } from '../test/manifest.ts';
import { writeGeneratedTestModule } from './generated-module.ts';

const compiledEntry = async (app: CompiledMcpApp, host: string): Promise<CompiledBrowserTestApp> => {
  const html = await readFile(app.output, 'utf8');
  const bytes = Buffer.byteLength(html, 'utf8');
  if (bytes > MAX_APP_HTML_BYTES) {
    throw new Error([
      `Compiled MCP App HTML exceeds the ${String(MAX_APP_HTML_BYTES)} byte browser harness bound.`,
      `  proof level: ${proofLevelLabel(BROWSER_APP_PROOF_LEVEL)}`,
      `  app:         ${app.name} (${app.resourceUri}, target ${app.target})`,
      `  output:      ${app.output}`,
      `  bytes:       ${String(bytes)}`,
    ].join('\n'));
  }
  return Object.freeze({
    html,
    name: app.name,
    output: app.output,
    proofLevel: BROWSER_APP_PROOF_LEVEL,
    resourceUri: app.resourceUri,
    serverIds: [...app.serverIds],
    target: host,
  });
};

export const browserTestSetupSource = (registry: AgentBrowserTestRegistry): string => [
  '// @generated by agent-bundle/rstest. Do not edit: rerun Rstest to regenerate.',
  `const registry = ${JSON.stringify(registry)};`,
  `globalThis[Symbol.for(${JSON.stringify(AGENT_BROWSER_TEST_REGISTRY_SYMBOL_KEY)})] = registry;`,
  '',
].join('\n');

/**
 * `hosts` names the host each compiled app mounts as, by app name. The
 * compiled HTML is the same for every host of the selection; the host is the
 * projection context the harness mounts under (#592).
 */
export const writeBrowserTestSetup = async (
  projectRoot: string,
  compiled: readonly CompiledMcpApp[],
  hosts: Readonly<Record<string, string>>,
): Promise<string> => {
  const apps = Object.fromEntries(
    await Promise.all(compiled.map(async (app) => {
      const host = hosts[app.name];
      if (host === undefined) {
        throw new Error(`Compiled MCP App ${JSON.stringify(app.name)} has no browser mount host.`);
      }
      return [app.name, await compiledEntry(app, host)] as const;
    })),
  );
  const registry: AgentBrowserTestRegistry = Object.freeze({
    apps,
    version: AGENT_BROWSER_TEST_REGISTRY_VERSION,
  });
  return writeGeneratedTestModule(projectRoot, 'browser-app-setup.mjs', browserTestSetupSource(registry));
};
