import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { generatedMetaModuleSource, metaModuleSpecifier, projectMeta } from '../build/meta.ts';
import {
  META_UNAVAILABLE_CODE,
  META_UNAVAILABLE_MESSAGE,
} from '../meta-diagnostic.ts';
import { type AgentBundleTestManifest, isFallbackPluginIdentity } from '../test/manifest.ts';

/**
 * The `resolve.alias` key both Rstest presets set for `agent-bundle/meta`.
 * The trailing `$` is Rspack's exact-match marker — the same key the browser
 * MCP App compiler uses — so `agent-bundle/meta/anything` never matches.
 */
export const metaModuleAliasKey = `${metaModuleSpecifier}$`;

const metaBindings = ['meta', 'name', 'packageName', 'packageVersion', 'version'] as const;

/**
 * The module a pool serves when the compiler pass produced no plugin model:
 * the configuration could not be loaded or normalized, so there is no
 * identity to stamp and stamping the manifest placeholder would hand
 * application code a fabricated one. Every binding throws the same `AB4760`
 * diagnostic the published module raises, with the recovery this situation
 * actually has — the compiler diagnostics — instead of the generic one. The
 * source is self-contained so it loads however the consumer resolved
 * `agent-bundle`.
 */
export const unavailableMetaModuleSource = (manifest: AgentBundleTestManifest): string => {
  const prepared = manifest.configPath ?? manifest.projectRoot;
  const diagnostics = manifest.diagnostics.filter((diagnostic) => diagnostic.severity === 'error');
  const message = [
    `[${META_UNAVAILABLE_CODE}] ${META_UNAVAILABLE_MESSAGE}`,
    `  This Rstest pool has no project identity to serve: preparing ${prepared} produced no plugin model.`,
    ...(diagnostics.length === 0
      ? []
      : ['  compiler diagnostics:', ...diagnostics.map((diagnostic) => `    [${diagnostic.code}] ${diagnostic.message}`)]),
  ].join('\n');
  const recovery = 'Fix the compiler diagnostics reported above so agent-bundle.config.ts loads and normalizes, then rerun Rstest; '
    + 'the preset regenerates this module with the project identity.';
  return [
    '// @generated by agent-bundle/rstest. Do not edit: rerun Rstest to regenerate.',
    '//',
    '// The compiler pass produced no plugin model, so `agent-bundle/meta` has no',
    '// identity in this pool. Every binding throws AB4760 through a hoisted',
    '// function so the failure is this diagnostic, never a TDZ ReferenceError.',
    'function throwUnavailable() {',
    `  const error = new Error(${JSON.stringify(`${message}\n  recovery: ${recovery}`)});`,
    "  error.name = 'AgentBundleMetaUnavailableError';",
    `  error.code = ${JSON.stringify(META_UNAVAILABLE_CODE)};`,
    `  error.recovery = ${JSON.stringify(recovery)};`,
    '  error.diagnostic = Object.freeze({',
    `    code: ${JSON.stringify(META_UNAVAILABLE_CODE)},`,
    `    message: ${JSON.stringify(message)},`,
    `    recovery: ${JSON.stringify(recovery)},`,
    "    severity: 'error',",
    '  });',
    '  throw error;',
    '}',
    ...metaBindings.map((binding) => `export const ${binding} = throwUnavailable();`),
    'export default throwUnavailable();',
    '',
  ].join('\n');
};

/**
 * The source a pool serves for `agent-bundle/meta` (issue #386). With a
 * model-backed identity it is the very module the build injects
 * (`generatedMetaModuleSource` over `projectMeta`), fed from the manifest's
 * plugin identity — the identity the same compiler pass reports in
 * `initialize` — so a source module importing `{ name, version }` observes
 * under a test exactly what a compiled surface would. Without one — the
 * manifest still carries the frozen sentinel object — it is the throwing
 * module above: the placeholder identity is never served.
 */
export const testMetaModuleSource = (manifest: AgentBundleTestManifest): string =>
  isFallbackPluginIdentity(manifest.plugin)
    ? unavailableMetaModuleSource(manifest)
    : generatedMetaModuleSource(projectMeta(manifest.plugin));

/**
 * Writes the identity module beside the generated route registry under the
 * project's `.agent-bundle/test` directory, which Rstest bundles like
 * project source, and returns its path for the alias.
 */
export const writeTestMetaModule = async (
  projectRoot: string,
  manifest: AgentBundleTestManifest,
): Promise<string> => {
  const target = resolve(projectRoot, '.agent-bundle', 'test', 'meta.mjs');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, testMetaModuleSource(manifest), 'utf8');
  return target;
};

/** The `resolve.alias` record routing the reserved specifier to a written identity module. */
export const metaModuleAlias = (metaModulePath: string): { [specifier: string]: string } =>
  ({ [metaModuleAliasKey]: metaModulePath });
