import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { AGENT_TEST_REGISTRY_SYMBOL_KEY, AGENT_TEST_REGISTRY_VERSION } from '../test/registry.ts';
import type { AgentBundleTestManifest, TestableRouteDescriptor } from '../test/manifest.ts';
import type { RenderableRouteKind } from '../test/types.ts';

const renderableKinds: ReadonlySet<string> = new Set<RenderableRouteKind>([
  'cli',
  'event-route',
  'prompt',
  'resource',
  'script',
  'tool',
]);

/**
 * Route modules the route-unit level can render. App routes are browser
 * components, so this generated module never pulls one into the Node test
 * bundle; the browser proof level compiles them instead.
 */
const renderableRoutes = (manifest: AgentBundleTestManifest): readonly TestableRouteDescriptor[] =>
  Object.values(manifest.routes)
    .filter((route) => renderableKinds.has(route.kind))
    .sort((left, right) => left.id.localeCompare(right.id));

/** Bundler-resolvable module specifier for one route module path. */
const specifier = (source: string): string => source.replaceAll('\\', '/');

export const routeTestSetupSource = (manifest: AgentBundleTestManifest): string => {
  const loaders = renderableRoutes(manifest)
    .map((route) => `    ${JSON.stringify(route.id)}: () => import(${JSON.stringify(specifier(route.source))}),`);
  return [
    '// @generated by agent-bundle/rstest. Do not edit: rerun Rstest to regenerate.',
    '//',
    '// The Rstest configuration compiled the project once and wrote the route',
    '// inventory here. Test workers read it through a realm global, so the',
    '// helpers in agent-bundle/test never recompile the project.',
    `const registry = {`,
    '  loaders: {',
    ...loaders,
    '  },',
    `  manifest: JSON.parse(${JSON.stringify(JSON.stringify(manifest))}),`,
    `  version: ${String(AGENT_TEST_REGISTRY_VERSION)},`,
    '};',
    '',
    `globalThis[Symbol.for(${JSON.stringify(AGENT_TEST_REGISTRY_SYMBOL_KEY)})] = registry;`,
    '',
  ].join('\n');
};

/**
 * Writes the generated route registry into the project's own `.agent-bundle`
 * state directory. That directory is already ignored by source discovery, the
 * dev watcher, and version control, and — unlike `node_modules` — Rstest
 * bundles files under it, so the generated route imports compile with the
 * project's own transforms. The file carries no imports of its own beyond the
 * project's route modules, so it loads identically however the consumer
 * resolved `agent-bundle`.
 */
export const writeRouteTestSetup = async (
  projectRoot: string,
  manifest: AgentBundleTestManifest,
): Promise<string> => {
  const target = resolve(projectRoot, '.agent-bundle', 'test', 'route-setup.mjs');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, routeTestSetupSource(manifest), 'utf8');
  return target;
};
