packages:
  - packages/*
  - packages/workbench/src/inspector
  - examples/*
allowBuilds:
  '@google/genai': false
  msgpackr-extract: false
  protobufjs: false
minimumReleaseAgeExclude:
  - '@rsbuild/core@2.2.1'
  - '@effect/tsgo-darwin-arm64@0.39.0'
  - '@effect/tsgo-darwin-x64@0.39.0'
  - '@effect/tsgo-linux-arm64@0.39.0'
  - '@effect/tsgo-linux-arm@0.39.0'
  - '@effect/tsgo-linux-x64@0.39.0'
  - '@effect/tsgo-win32-arm64@0.39.0'
  - '@effect/tsgo-win32-x64@0.39.0'
  - '@effect/tsgo@0.39.0'
