import { existsSync, statSync } from 'node:fs';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { createJiti } from 'jiti';
import { stringify as stringifyYaml } from 'yaml';

import { generatedMetaModuleSource, metaModuleSpecifier } from '../build/meta.ts';
import type { Diagnostic } from '../core/diagnostics.ts';
import { errorMessage } from '../core/errors.ts';
import { isPlainRecord } from '../core/strict-json.ts';
import type { AgentBundleMeta } from '../meta.ts';
import { MarkdownRenderError, renderElementToMarkdown } from './render-markdown.ts';

/**
 * The rendered-skill convention: `src/skills/<name>/SKILL.tsx` (or `.ts`)
 * default-exports a component and exports a `frontmatter` record; the build
 * compiles the rendered tree to the `SKILL.md` document every host consumes.
 * A hand-authored `SKILL.md` in the same directory always wins (config beats
 * convention; an authored file beats a generated one).
 */
const renderedSkillFileNames = ['SKILL.tsx', 'SKILL.ts'] as const;

/** The source file behind a rendered skill in `skillDir`, when the convention applies. */
export const renderedSkillSourceAt = (skillDir: string): string | undefined => {
  for (const fileName of renderedSkillFileNames) {
    const candidate = join(skillDir, fileName);
    try {
      if (existsSync(candidate) && statSync(candidate).isFile()) return candidate;
    } catch {
      // A racing deletion means the convention does not apply.
    }
  }
  return undefined;
};

/** True for the conventional rendered-skill source file names. */
export const isRenderedSkillSourceName = (fileName: string): boolean =>
  (renderedSkillFileNames as readonly string[]).includes(fileName);

export interface CompiledRenderedSkill {
  readonly authoredTargets?: unknown;
  readonly body: string;
  readonly frontmatter: Record<string, unknown>;
  /** The full compiled document: YAML frontmatter followed by the rendered body. */
  readonly markdown: string;
}

export type RenderedSkillCompilation =
  | { readonly document: CompiledRenderedSkill; readonly status: 'compiled' }
  | { readonly diagnostic: Diagnostic; readonly status: 'failed' };

const failure = (code: string, message: string, sourcePath: string): RenderedSkillCompilation => ({
  diagnostic: { code, message, severity: 'error', sourcePath },
  status: 'failed',
});

/** What the loader serves to a rendered skill module beyond the project's own code. */
export interface RenderedSkillLoaderOptions {
  /**
   * The project identity `agent-bundle/meta` resolves to while the module
   * evaluates — the same constants the compiler stamps into every built
   * surface. Without it the specifier resolves to the published module,
   * which throws `AB4760` (no compiler, no identity).
   */
  readonly meta?: AgentBundleMeta;
}

/**
 * The element factory a rendered skill's JSX compiles against. It builds the
 * plain `{ type, props, key }` objects `renderElementToMarkdown` walks, with
 * React's fragment symbol, and never touches React: the consumer's `react`
 * resolves by process condition (`--conditions=react-server` in the
 * route-unit pool selects the server build) while jiti resolves package
 * subpaths without those conditions, so binding `react/jsx-runtime` from
 * one build to `react` from the other throws inside React (#441). The skill
 * renderer needs no React internals at all, so it does not resolve any.
 */
const jsxRuntimeModuleSource = [
  '// Generated by agent-bundle for one rendered-skill evaluation. Do not edit.',
  "const elementType = Symbol.for('react.transitional.element');",
  "export const Fragment = Symbol.for('react.fragment');",
  'const element = (type, props, key) => ({',
  '  $$typeof: elementType,',
  '  key: key === undefined ? null : String(key),',
  '  props,',
  '  ref: null,',
  '  type,',
  '});',
  'export const jsx = element;',
  'export const jsxs = element;',
  'export const jsxDEV = element;',
  '',
].join('\n');

const reactJsxRuntimeSpecifiers = ['react/jsx-runtime', 'react/jsx-dev-runtime'] as const;

/**
 * Writes the generated modules one evaluation aliases into a private
 * temporary directory and returns jiti's alias record. Nothing is written
 * under the project: discovery runs during `validate`, which never touches
 * the tree it validates.
 */
const writeLoaderModules = async (
  directory: string,
  options: RenderedSkillLoaderOptions,
): Promise<Record<string, string>> => {
  const jsxRuntimePath = join(directory, 'jsx-runtime.mjs');
  const writes = [writeFile(jsxRuntimePath, jsxRuntimeModuleSource, 'utf8')];
  const alias: Record<string, string> = Object.fromEntries(
    reactJsxRuntimeSpecifiers.map((specifier) => [specifier, jsxRuntimePath]),
  );
  if (options.meta !== undefined) {
    const metaPath = join(directory, 'meta.mjs');
    writes.push(writeFile(metaPath, generatedMetaModuleSource(options.meta), 'utf8'));
    alias[metaModuleSpecifier] = metaPath;
  }
  await Promise.all(writes);
  return alias;
};

/**
 * Loads and compiles one rendered skill source to its Markdown document. The
 * module executes through the same jiti pipeline that already runs consumer
 * TypeScript at config-load time. Its JSX compiles against the loader's own
 * element factory rather than the consumer's `react/jsx-runtime`, and
 * `agent-bundle/meta` resolves to the project identity when the caller
 * supplies one; project code the skill imports resolves from the project as
 * usual.
 */
export const compileRenderedSkill = async (
  source: string,
  options: RenderedSkillLoaderOptions = {},
): Promise<RenderedSkillCompilation> => {
  let moduleExports: Record<string, unknown>;
  const loaderDirectory = await mkdtemp(join(tmpdir(), 'agent-bundle-rendered-skill-'));
  try {
    const alias = await writeLoaderModules(loaderDirectory, options);
    const jiti = createJiti(source, {
      alias,
      interopDefault: true,
      jsx: { runtime: 'automatic' },
      moduleCache: false,
      nativeModules: ['typescript'],
    });
    moduleExports = await jiti.import<Record<string, unknown>>(source);
  } catch (error) {
    return failure('AB3003', `Rendered Skill module failed to load: ${errorMessage(error)}`, source);
  } finally {
    await rm(loaderDirectory, { force: true, recursive: true });
  }

  const component = moduleExports.default;
  if (typeof component !== 'function') {
    return failure(
      'AB3004',
      'Rendered Skill module must default-export a component function.',
      source,
    );
  }
  const frontmatter = moduleExports.frontmatter;
  if (!isPlainRecord(frontmatter)) {
    return failure(
      'AB3004',
      'Rendered Skill module must export a `frontmatter` record with the skill name and description.',
      source,
    );
  }

  let body: string;
  try {
    body = await renderElementToMarkdown({ props: {}, type: component });
  } catch (error) {
    return failure(
      'AB3005',
      error instanceof MarkdownRenderError
        ? error.message
        : `Rendered Skill content failed to render: ${errorMessage(error)}`,
      source,
    );
  }

  let serializedFrontmatter: string;
  try {
    serializedFrontmatter = stringifyYaml(frontmatter);
  } catch (error) {
    return failure(
      'AB3004',
      `Rendered Skill frontmatter is not serializable YAML: ${errorMessage(error)}`,
      source,
    );
  }

  const snapshot = structuredClone(frontmatter);
  const skillExport = moduleExports.skill;
  const authoredTargets = isPlainRecord(moduleExports.targets)
    ? structuredClone(moduleExports.targets)
    : isPlainRecord(skillExport) && isPlainRecord(skillExport.targets)
      ? structuredClone(skillExport.targets)
      : undefined;
  return {
    document: {
      ...(authoredTargets === undefined ? {} : { authoredTargets }),
      body,
      frontmatter: snapshot,
      markdown: `---\n${serializedFrontmatter}---\n\n${body}`,
    },
    status: 'compiled',
  };
};
