import type { NormalizedPlugin } from '../core/types.ts';
import {
  sortedEntries,
  sourceInputs,
  type TargetArtifactPlan,
  type TargetArtifactWrite,
} from '../adapters/types.ts';
import {
  installReceiptFile,
  installReceiptFormat,
  installSurfaceMarkerFiles,
  preservedRuntimeEntries,
} from './receipt.ts';

export type BuiltInTarget = 'claude' | 'codex' | 'cursor' | 'plugin' | 'portable';

const marketplaceName = (model: NormalizedPlugin): string => `${model.metadata.name}-marketplace`;

const pluginId = (model: NormalizedPlugin): string => `${model.metadata.name}@${marketplaceName(model)}`;

const header = (model: NormalizedPlugin): string[] => [
  `# Install ${model.metadata.name}`,
  '',
  model.metadata.description ?? model.metadata.name,
  '',
  `Version: \`${model.metadata.version}\``,
  '',
  'Run these commands from this bundle directory.',
  '',
];

const claudeInstructions = (model: NormalizedPlugin): string[] => [
  '## Claude Code',
  '',
  'Claude Code installs this bundle through its local marketplace contract:',
  '',
  '```sh',
  'claude plugin marketplace add ./',
  `claude plugin install ${model.metadata.name}@${marketplaceName(model)} --scope user`,
  '```',
  '',
  'Replace `user` with `project` or `local` when that Claude scope is intended.',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  '`claude plugin update` is version-gated: when the bundle content changed but `version` did not,',
  'it reports the plugin is already at the latest version and leaves the cached copy stale.',
  'Uninstall and install again instead (`--keep-data` preserves the plugin\'s persistent data):',
  '',
  '```sh',
  `claude plugin uninstall ${pluginId(model)} --scope user --keep-data`,
  'claude plugin marketplace add ./',
  `claude plugin install ${pluginId(model)} --scope user`,
  '```',
  '',
  '`agent-bundle install claude --from ./` runs this sequence automatically when the installed',
  'copy has the same version but a different content hash; `--replace` (alias `--force`) forces it.',
  '',
];

const codexInstructions = (model: NormalizedPlugin): string[] => [
  '## Codex',
  '',
  'Codex installs this bundle from its local marketplace snapshot:',
  '',
  '```sh',
  'codex plugin marketplace add ./',
  `codex plugin add ${model.metadata.name}@${marketplaceName(model)}`,
  '```',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  '`codex plugin add` re-copies the marketplace snapshot but never deletes files a rebuild removed.',
  'Remove and add again for a clean same-version copy:',
  '',
  '```sh',
  `codex plugin remove ${pluginId(model)}`,
  'codex plugin marketplace add ./',
  `codex plugin add ${pluginId(model)}`,
  '```',
  '',
  '`agent-bundle install codex --from ./` runs this sequence automatically when the installed',
  'copy has the same version but a different content hash; `--replace` (alias `--force`) forces it.',
  '',
];

const cursorInstructions = (model: NormalizedPlugin): string[] => [
  '## Cursor',
  '',
  'Cursor has no non-interactive plugin install command. Use the bundled safe-copy installer:',
  '',
  '```sh',
  'node ./install.mjs',
  '```',
  '',
  `It installs to \`~/.cursor/plugins/local/${model.metadata.name}\`. Restart Cursor or run`,
  '`Developer: Reload Window` after installation.',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  `The installer writes an install receipt (\`${installReceiptFile}\`: plugin, version, content hash,`,
  'owned files) beside the plugin manifest. Re-running `node ./install.mjs` on an identical artifact',
  'is a no-op that says so. When the installed copy has the same version but different content, the',
  'installer replaces its owned files in place and leaves runtime state (`state/`) untouched:',
  '',
  '```sh',
  'node ./install.mjs            # same-version content drift of a receipt-managed copy is replaced',
  'node ./install.mjs --replace  # also replace a different installed version, or adopt a pre-receipt copy',
  '```',
  '',
  '`--force` is an alias for `--replace`. A directory that is not an agent-bundle install of this',
  'plugin is always refused with an installed-versus-artifact content-hash comparison; remove it',
  'manually. `agent-bundle install cursor --from ./ [--replace]` applies the same policy.',
  '',
];

const portableInstructions = (): string[] => [
  '## Portable Agent Plugin',
  '',
  'Portable is a distribution profile, not a host runtime with one universal install location.',
  'This bundle follows the Agent Plugins open standard (Agent Plugins 1.0.0, https://agent-plugins.org).',
  'Cursor loads this format natively from `~/.cursor/plugins/local/<name>`; restart Cursor or run',
  '`Developer: Reload Window` after copying it. Codex, VS Code, GitHub Copilot, Kiro, and ChatGPT',
  'are also native clients. The bundled installer provides the Cursor local copy:',
  '',
  '```sh',
  'node ./install.mjs',
  '```',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  `The installer records an install receipt (\`${installReceiptFile}\`) and replaces its owned files in`,
  'place when the same version was rebuilt with different content; runtime state (`state/`) is never',
  'touched. Pass `--replace` (alias `--force`) to replace a different installed version or to adopt a',
  'copy installed before receipts existed. Foreign directories are refused with a content-hash',
  'comparison. For Codex and other native clients, remove and re-add the plugin through the client',
  'when only content changed at the same version.',
  '',
];

const installMarkdown = (model: NormalizedPlugin, target: BuiltInTarget): string => {
  const sections = (() => {
    switch (target) {
      case 'claude':
        return claudeInstructions(model);
      case 'codex':
        return codexInstructions(model);
      case 'cursor':
        return cursorInstructions(model);
      case 'portable':
        return portableInstructions();
      case 'plugin':
        return [...claudeInstructions(model), ...codexInstructions(model), ...cursorInstructions(model)];
      default: {
        const exhaustive: never = target;
        throw new TypeError(`Unknown built-in install target ${String(exhaustive)}.`);
      }
    }
  })();
  return [...header(model), ...sections].join('\n');
};

/**
 * The standalone Cursor safe-copy installer. It carries no imports from
 * agent-bundle, so it mirrors the receipt policy of `install/receipt.ts`
 * line for line: same receipt file and format, same owned-file hashing, same
 * ownership verdicts (receipt, legacy layout, foreign), and the same
 * owned-files-only in-place replacement. `tests/install-surface.test.ts` and
 * the host-install proofs pin the two implementations to each other.
 */
const cursorInstallerSource = (model: NormalizedPlugin): string => {
  const name = JSON.stringify(model.metadata.name);
  const version = JSON.stringify(model.metadata.version);
  return [
    '#!/usr/bin/env node',
    "import { createHash } from 'node:crypto';",
    "import { cp, lstat, mkdir, mkdtemp, readFile, readdir, rename, rm, rmdir, writeFile } from 'node:fs/promises';",
    "import { homedir } from 'node:os';",
    "import { basename, dirname, join, resolve } from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    `const pluginName = ${name};`,
    `const pluginVersion = ${version};`,
    `const receiptFile = ${JSON.stringify(installReceiptFile)};`,
    `const receiptFormat = ${JSON.stringify(installReceiptFormat)};`,
    `const preservedEntries = ${JSON.stringify(preservedRuntimeEntries)};`,
    `const markerFiles = ${JSON.stringify(installSurfaceMarkerFiles)};`,
    "const source = resolve(fileURLToPath(new URL('.', import.meta.url)));",
    "const cursorRoot = join(homedir(), '.cursor');",
    "const installRoot = join(cursorRoot, 'plugins', 'local');",
    'const destination = join(installRoot, pluginName);',
    "const usage = 'Usage: node install.mjs [--replace|--force] [--help]';",
    '',
    'let replace = false;',
    'for (const argument of process.argv.slice(2)) {',
    "  if (argument === '--replace' || argument === '--force') { replace = true; continue; }",
    "  if (argument === '--help' || argument === '-h') { console.log(usage); process.exit(0); }",
    '  console.error(`Unknown installer argument ${JSON.stringify(argument)}.\\n${usage}`);',
    '  process.exit(2);',
    '}',
    '',
    'const exists = async (path) => {',
    '  try { await lstat(path); return true; }',
    "  catch (error) { if (error?.code === 'ENOENT') return false; throw error; }",
    '};',
    "const unsupported = (relative) => new Error(`Refusing unsupported filesystem entry ${JSON.stringify(relative || '.')}.`);",
    "const toPosix = (path) => path.replaceAll('\\\\', '/');",
    'const short = (hash) => hash.slice(0, 12);',
    '',
    'const hashEntry = (hash, relative, bytes) => {',
    '  hash.update(toPosix(relative));',
    "  hash.update('\\0');",
    '  hash.update(bytes);',
    "  hash.update('\\0');",
    '};',
    '',
    '// Deterministic tree walk: symlinks and special files refused, the root receipt skipped.',
    'const inventory = async (root) => {',
    '  const rootMetadata = await lstat(root);',
    "  if (rootMetadata.isSymbolicLink() || !rootMetadata.isDirectory()) throw unsupported('.');",
    "  const hash = createHash('sha256');",
    '  const files = [];',
    '  const visit = async (relative) => {',
    '    const absolute = join(root, relative);',
    '    const metadata = await lstat(absolute);',
    '    if (metadata.isSymbolicLink() || (!metadata.isDirectory() && !metadata.isFile())) throw unsupported(relative);',
    '    if (metadata.isDirectory()) {',
    '      for (const entry of (await readdir(absolute)).sort((left, right) => left.localeCompare(right))) await visit(join(relative, entry));',
    '      return;',
    '    }',
    '    files.push(toPosix(relative));',
    '    hashEntry(hash, relative, await readFile(absolute));',
    '  };',
    '  for (const entry of (await readdir(root)).sort((left, right) => left.localeCompare(right))) {',
    '    if (entry === receiptFile) continue;',
    '    await visit(entry);',
    '  }',
    "  return { files, hash: hash.digest('hex') };",
    '};',
    '',
    '// Every directory on the way to a listed path must be a real directory (no symlinked ancestors);',
    '// an owned regular file that a rebuild turns into a directory leaves as stale first, so it is tolerated.',
    'const assertRealAncestors = async (root, files, ownedFiles = new Set()) => {',
    '  const checked = new Set();',
    '  for (const file of files) {',
    '    let directory = dirname(file);',
    "    while (directory !== '.' && directory !== '') {",
    '      if (!checked.has(directory)) {',
    '        checked.add(directory);',
    '        try {',
    '          const metadata = await lstat(join(root, directory));',
    '          if (metadata.isSymbolicLink()) throw unsupported(directory);',
    '          if (!metadata.isDirectory() && !(metadata.isFile() && ownedFiles.has(directory))) throw unsupported(directory);',
    "        } catch (error) { if (error?.code !== 'ENOENT') throw error; }",
    '      }',
    '      directory = dirname(directory);',
    '    }',
    '  }',
    '};',
    '',
    '// Hashes exactly the owned files; a missing owned file simply changes the digest.',
    'const hashOwned = async (root, files) => {',
    '  await assertRealAncestors(root, files);',
    "  const hash = createHash('sha256');",
    '  for (const relative of files) {',
    '    const absolute = join(root, relative);',
    '    let metadata;',
    "    try { metadata = await lstat(absolute); } catch (error) { if (error?.code === 'ENOENT') continue; throw error; }",
    '    if (metadata.isSymbolicLink() || !metadata.isFile()) throw unsupported(relative);',
    '    hashEntry(hash, relative, await readFile(absolute));',
    '  }',
    "  return hash.digest('hex');",
    '};',
    '',
    '// Receipt paths drive deletions: POSIX-relative only, no backslashes, no empty/./.. segments, no drive letter.',
    "const safeRelative = (value) => typeof value === 'string' && value.length > 0 && value !== receiptFile &&",
    "  !value.includes('\\\\') && !value.startsWith('/') && !/^[a-z]:/i.test(value) &&",
    "  value.split('/').every((segment) => segment !== '' && segment !== '.' && segment !== '..');",
    '',
    'const readReceipt = async (root) => {',
    '  let value;',
    "  try { value = JSON.parse(await readFile(join(root, receiptFile), 'utf8')); }",
    "  catch (error) { if (error?.code === 'ENOENT' || error instanceof SyntaxError) return undefined; throw error; }",
    "  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined;",
    '  // Same shape check as the core reader: a receipt missing any field reads as absent.',
    "  if (value.format !== receiptFormat || typeof value.plugin !== 'string' || typeof value.version !== 'string' ||",
    "    typeof value.host !== 'string' || typeof value.contentHash !== 'string' || typeof value.installedAt !== 'string' ||",
    '    !Array.isArray(value.files) || !value.files.every(safeRelative)) return undefined;',
    '  return value;',
    '};',
    '',
    'const readManifest = async (root) => {',
    "  for (const manifest of ['.cursor-plugin/plugin.json', 'plugin.json']) {",
    '    try {',
    "      const value = JSON.parse(await readFile(join(root, manifest), 'utf8'));",
    "      if (value !== null && typeof value === 'object' && typeof value.name === 'string') {",
    "        return { name: value.name, ...(typeof value.version === 'string' ? { version: value.version } : {}) };",
    '      }',
    "    } catch (error) { if (error?.code !== 'ENOENT' && !(error instanceof SyntaxError)) throw error; }",
    '  }',
    '  return undefined;',
    '};',
    '',
    'const hasMarkers = async (root) => {',
    '  for (const marker of markerFiles) if (!(await exists(join(root, marker)))) return false;',
    '  return true;',
    '};',
    '',
    'const receiptFor = (tree) => JSON.stringify({',
    '  contentHash: tree.hash,',
    '  files: tree.files,',
    '  format: receiptFormat,',
    "  host: 'cursor',",
    '  installedAt: new Date().toISOString(),',
    '  plugin: pluginName,',
    '  version: pluginVersion,',
    "}, null, 2) + '\\n';",
    '',
    '// Staged sibling copy on the destination filesystem so every later rename is atomic.',
    'const stage = async () => {',
    '  const parent = await mkdtemp(join(installRoot, `.${basename(destination)}.stage-`));',
    "  const root = join(parent, 'bundle');",
    '  try {',
    '    await cp(source, root, { errorOnExist: true, force: false, recursive: true, verbatimSymlinks: true });',
    '    await rm(join(root, receiptFile), { force: true });',
    '    const staged = await inventory(root);',
    "    await writeFile(join(root, receiptFile), receiptFor(staged), 'utf8');",
    '    return { inventory: staged, parent, root };',
    '  } catch (error) {',
    '    await rm(parent, { force: true, recursive: true });',
    '    throw error;',
    '  }',
    '};',
    '',
    'const pruneEmptyDirectories = async (removed) => {',
    '  const candidates = new Set();',
    '  for (const file of removed) {',
    '    let directory = dirname(file);',
    "    while (directory !== '.' && directory !== '') { candidates.add(directory); directory = dirname(directory); }",
    '  }',
    '  for (const directory of [...candidates].sort((left, right) => right.length - left.length)) {',
    '    try { await rmdir(join(destination, directory)); }',
    "    catch (error) { if (!['ENOTEMPTY', 'ENOENT', 'EEXIST'].includes(error?.code)) throw error; }",
    '  }',
    '};',
    '',
    'if (!(await exists(cursorRoot)) || !(await lstat(cursorRoot)).isDirectory()) {',
    '  throw new Error(`Cursor is not installed in ${cursorRoot}.`);',
    '}',
    'await mkdir(installRoot, { recursive: true });',
    'const artifact = await inventory(source);',
    '',
    'if (!(await exists(destination))) {',
    '  const staged = await stage();',
    '  try {',
    '    await rename(staged.root, destination);',
    '    console.log(`Installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '  } finally {',
    '    await rm(staged.parent, { force: true, recursive: true });',
    '  }',
    '  process.exit(0);',
    '}',
    'if (source === destination) {',
    '  console.log(`Already installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '  process.exit(0);',
    '}',
    '',
    'const destinationMetadata = await lstat(destination);',
    "if (destinationMetadata.isSymbolicLink() || !destinationMetadata.isDirectory()) throw unsupported('.');",
    'const receipt = await readReceipt(destination);',
    'const manifest = await readManifest(destination);',
    'let ownership;',
    'let installedHash;',
    'if (receipt !== undefined && receipt.plugin === pluginName) {',
    "  ownership = 'receipt';",
    '  installedHash = await hashOwned(destination, receipt.files);',
    '} else {',
    '  installedHash = (await inventory(destination)).hash;',
    "  ownership = receipt === undefined && manifest?.name === pluginName && await hasMarkers(destination) ? 'legacy' : 'foreign';",
    '}',
    "const installedVersion = manifest?.version ?? (ownership === 'receipt' ? receipt.version : undefined);",
    "const installedName = manifest?.name ?? (ownership === 'receipt' ? receipt.plugin : pluginName);",
    '// A receipt-managed copy is current only when its recorded inventory matches the artifact too.',
    "const inventoryMatches = ownership !== 'receipt' ||",
    '  (receipt.files.length === artifact.files.length && receipt.files.every((file, index) => file === artifact.files[index]));',
    'if (installedHash === artifact.hash && inventoryMatches) {',
    "  if (ownership === 'legacy' && replace) {",
    '    // Byte-identical pre-receipt copy: adoption only writes the receipt.',
    '    const temporary = join(destination, `${receiptFile}.${process.pid}.tmp`);',
    "    await writeFile(temporary, receiptFor(artifact), 'utf8');",
    '    await rename(temporary, join(destination, receiptFile));',
    '    console.log(`Adopted ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '    process.exit(0);',
    '  }',
    '  console.log(`Already installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '  process.exit(0);',
    '}',
    'const verdict = installedVersion === undefined',
    "  ? 'different content, installed version unknown'",
    "  : installedVersion === pluginVersion ? 'same version, different content' : 'different version';",
    "const detail = `installed ${installedName}@${installedVersion ?? 'unknown version'} content ${short(installedHash)} ` +",
    '  `vs artifact ${pluginName}@${pluginVersion} content ${short(artifact.hash)} (${verdict})`;',
    "if (ownership === 'foreign') {",
    '  throw new Error(`Refusing foreign install at ${destination}: ${detail}; the directory is not an agent-bundle install of ` +',
    '    `${pluginName}, so --replace does not apply. Remove it manually if it is stale.`);',
    '}',
    'if (installedVersion !== undefined && installedVersion !== pluginVersion && !replace) {',
    '  throw new Error(`Refusing version collision at ${destination}: ${detail}. Re-run with --replace to replace this agent-bundle install.`);',
    '}',
    "if (ownership === 'legacy' && !replace) {",
    '  throw new Error(`Refusing content collision at ${destination}: ${detail}; this copy predates install receipts. ` +',
    "    'Re-run with --replace once to adopt it; later same-version rebuilds replace automatically.');",
    '}',
    '',
    '// Owned-files-only replacement: stale owned files leave first, staged files rename over their',
    '// predecessors, and the receipt lands last as the commit marker. Unowned entries (runtime state) stay.',
    'const staged = await stage();',
    'try {',
    "  const owned = ownership === 'receipt'",
    '    ? receipt.files',
    "    : (await inventory(destination)).files.filter((file) => !preservedEntries.includes(file.split('/')[0]));",
    '  const ownedSet = new Set(owned);',
    '  await assertRealAncestors(destination, owned);',
    '  await assertRealAncestors(destination, staged.inventory.files, ownedSet);',
    '  // Case-insensitive filesystems: a case-only rename of an owned path is the same inode, not a collision.',
    '  let ownedIdentities;',
    '  const isOwnedIdentity = async (path) => {',
    '    const candidate = await lstat(path);',
    '    ownedIdentities ??= (await Promise.all(owned.map(async (file) => {',
    '      try { return await lstat(join(destination, file)); }',
    "      catch (error) { if (error?.code === 'ENOENT') return undefined; throw error; }",
    '    }))).filter((metadata) => metadata !== undefined);',
    '    return ownedIdentities.some((metadata) => metadata.dev === candidate.dev && metadata.ino === candidate.ino);',
    '  };',
    '  // An existing directory at an incoming file path is fine only when everything beneath it is owned.',
    '  const isWhollyOwnedDirectory = async (file) =>',
    '    (await inventory(join(destination, file))).files.every((entry) => ownedSet.has(`${file}/${entry}`));',
    '  const collisions = [];',
    '  for (const file of staged.inventory.files) {',
    '    if (ownedSet.has(file)) continue;',
    '    const target = join(destination, file);',
    '    let metadata;',
    "    try { metadata = await lstat(target); } catch (error) { if (error?.code === 'ENOENT' || error?.code === 'ENOTDIR') continue; throw error; }",
    '    const tolerated = metadata.isDirectory() && !metadata.isSymbolicLink()',
    '      ? await isWhollyOwnedDirectory(file)',
    '      : await isOwnedIdentity(target);',
    '    if (!tolerated) collisions.push(file);',
    '  }',
    '  if (collisions.length > 0) {',
    "    throw new Error(`Refusing to overwrite unowned files at ${destination}: ${collisions.join(', ')}. Move them aside manually before replacing.`);",
    '  }',
    '  const incoming = new Set(staged.inventory.files);',
    '  const stale = owned.filter((file) => !incoming.has(file));',
    '  for (const file of stale) await rm(join(destination, file), { force: true });',
    '  await pruneEmptyDirectories(stale);',
    '  for (const file of staged.inventory.files) {',
    '    const target = join(destination, file);',
    '    await mkdir(dirname(target), { recursive: true });',
    '    await rename(join(staged.root, file), target);',
    '  }',
    '  await rename(join(staged.root, receiptFile), join(destination, receiptFile));',
    '  console.log(`Replaced ${pluginName}@${pluginVersion} at ${destination} (content ${short(installedHash)} -> ${short(artifact.hash)})`);',
    '} finally {',
    '  await rm(staged.parent, { force: true, recursive: true });',
    '}',
    '',
  ].join('\n');
};

const needsCursorInstaller = (target: BuiltInTarget): boolean =>
  target === 'cursor' || target === 'plugin' || target === 'portable';

export const installSurfaceRequirements = (
  target: string,
): readonly string[] => {
  if (target === 'cursor' || target === 'plugin' || target === 'portable') {
    return Object.freeze(['INSTALL.md', 'install.mjs']);
  }
  if (target === 'claude' || target === 'codex') {
    return Object.freeze(['INSTALL.md']);
  }
  return Object.freeze([]);
};

export const installSurfaceEntries = (
  model: NormalizedPlugin,
  target: BuiltInTarget,
): readonly TargetArtifactWrite[] => Object.freeze([
  Object.freeze({
    content: installMarkdown(model, target),
    kind: 'write' as const,
    relativePath: 'INSTALL.md',
    sourceInputs: sourceInputs(model.metadata.provenance.sourcePath),
  }),
  ...(needsCursorInstaller(target)
    ? [Object.freeze({
        content: cursorInstallerSource(model),
        kind: 'write' as const,
        relativePath: 'install.mjs',
        sourceInputs: sourceInputs(model.metadata.provenance.sourcePath),
      })]
    : []),
]);

export const withInstallSurface = (
  plan: TargetArtifactPlan,
  model: NormalizedPlugin,
  target: BuiltInTarget,
): TargetArtifactPlan => Object.freeze({
  ...plan,
  entries: sortedEntries([...plan.entries, ...installSurfaceEntries(model, target)]),
});
