import type { NormalizedPlugin } from '../core/types.ts';
import {
  sortedEntries,
  sourceInputs,
  type TargetArtifactPlan,
  type TargetArtifactWrite,
} from '../adapters/types.ts';
import {
  installReceiptFile,
  installReceiptFormat,
  installSurfaceMarkerFiles,
  preservedRuntimeEntries,
} from './receipt.ts';

export type BuiltInTarget = 'claude' | 'codex' | 'cursor' | 'plugin' | 'portable';

const marketplaceName = (model: NormalizedPlugin): string => `${model.metadata.name}-marketplace`;

const pluginId = (model: NormalizedPlugin): string => `${model.metadata.name}@${marketplaceName(model)}`;

const header = (model: NormalizedPlugin): string[] => [
  `# Install ${model.metadata.name}`,
  '',
  model.metadata.description ?? model.metadata.name,
  '',
  `Version: \`${model.metadata.version}\``,
  '',
  'Run these commands from this bundle directory.',
  '',
];

const claudeInstructions = (model: NormalizedPlugin): string[] => [
  '## Claude Code',
  '',
  'Claude Code installs this bundle through its local marketplace contract:',
  '',
  '```sh',
  'claude plugin marketplace add ./',
  `claude plugin install ${model.metadata.name}@${marketplaceName(model)} --scope user`,
  '```',
  '',
  'Replace `user` with `project` or `local` when that Claude scope is intended.',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  '`claude plugin update` is version-gated: when the bundle content changed but `version` did not,',
  'it reports the plugin is already at the latest version and leaves the cached copy stale.',
  'Uninstall and install again instead (`--keep-data` preserves the plugin\'s persistent data):',
  '',
  '```sh',
  `claude plugin uninstall ${pluginId(model)} --scope user --keep-data`,
  'claude plugin marketplace add ./',
  `claude plugin install ${pluginId(model)} --scope user`,
  '```',
  '',
  '`agent-bundle install claude --from ./` runs this sequence automatically when the installed',
  'copy has the same version but a different content hash; `--replace` (alias `--force`) forces it.',
  '',
];

const codexInstructions = (model: NormalizedPlugin): string[] => [
  '## Codex',
  '',
  'Codex installs this bundle from its local marketplace snapshot:',
  '',
  '```sh',
  'codex plugin marketplace add ./',
  `codex plugin add ${model.metadata.name}@${marketplaceName(model)}`,
  '```',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  '`codex plugin add` re-copies the marketplace snapshot but never deletes files a rebuild removed.',
  'Remove and add again for a clean same-version copy:',
  '',
  '```sh',
  `codex plugin remove ${pluginId(model)}`,
  'codex plugin marketplace add ./',
  `codex plugin add ${pluginId(model)}`,
  '```',
  '',
  '`agent-bundle install codex --from ./` runs this sequence automatically when the installed',
  'copy has the same version but a different content hash; `--replace` (alias `--force`) forces it.',
  '',
];

const cursorInstructions = (model: NormalizedPlugin): string[] => [
  '## Cursor',
  '',
  'Cursor has no non-interactive plugin install command. The bundled installer supports two delivery modes.',
  '',
  '### Local plugin (default)',
  '',
  '```sh',
  'node ./install.mjs',
  '```',
  '',
  `It safe-copies the bundle to \`~/.cursor/plugins/local/${model.metadata.name}\`. Restart Cursor or run`,
  '`Developer: Reload Window` after installation. Cursor loads rules, skills, MCP servers, and the',
  'manifest-declared `hooks/hooks.json` from that directory; plugin hooks run from the plugin root with',
  '`${CURSOR_PLUGIN_ROOT}` substituted and need no `~/.cursor/hooks.json` entry.',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  `The installer writes an install receipt (\`${installReceiptFile}\`: plugin, version, content hash,`,
  'owned files) beside the plugin manifest. Re-running `node ./install.mjs` on an identical artifact',
  'is a no-op that says so. When the installed copy has the same version but different content, the',
  'installer replaces its owned files in place and leaves runtime state (`state/`) untouched:',
  '',
  '```sh',
  'node ./install.mjs            # same-version content drift of a receipt-managed copy is replaced',
  'node ./install.mjs --replace  # also replace a different installed version, or adopt a pre-receipt copy',
  '```',
  '',
  '`--force` is an alias for `--replace`. A directory that is not an agent-bundle install of this',
  'plugin is always refused with an installed-versus-artifact content-hash comparison; remove it',
  'manually. `agent-bundle install cursor --from ./ [--replace]` applies the same policy.',
  '',
  '### Marketplace plugin',
  '',
  '```sh',
  'node ./install.mjs --mode marketplace',
  '```',
  '',
  `It stages a committed Git repository at \`~/.cursor/agent-bundle/marketplaces/${model.metadata.name}\` whose`,
  `\`.cursor-plugin/marketplace.json\` lists this plugin, then prints the exact Cursor step: Customize -> Plugins ->`,
  '"Add Plugins from Local Repository" -> select that directory -> Install. Cursor then shows the plugin as a',
  'marketplace install (not "local") and manages it from Customize. `git` must be on PATH. Verify with',
  '`agent-bundle doctor --host cursor`.',
  '',
];

const portableInstructions = (): string[] => [
  '## Portable Agent Plugin',
  '',
  'Portable is a distribution profile, not a host runtime with one universal install location.',
  'This bundle follows the Agent Plugins open standard (Agent Plugins 1.0.0, https://agent-plugins.org).',
  'Cursor loads this format natively from `~/.cursor/plugins/local/<name>`; restart Cursor or run',
  '`Developer: Reload Window` after copying it. Codex, VS Code, GitHub Copilot, Kiro, and ChatGPT',
  'are also native clients. The bundled installer provides the Cursor local copy:',
  '',
  '```sh',
  'node ./install.mjs',
  '```',
  '',
  '### Cursor placeholder expansion',
  '',
  'Cursor 3.18.25 spawns the stdio servers of an Agent Plugins package without expanding',
  '`${PLUGIN_ROOT}` / `${PLUGIN_DATA}` in `args`, `env` values, or `cwd`, without providing the',
  'reserved `PLUGIN_ROOT` / `PLUGIN_DATA` variables (spec §9.1), with an omitted `cwd` defaulting to',
  'the home directory, and with plugin-relative `./` commands resolved against the workspace folder',
  '(spec §7.2.1). The installer therefore rewrites `mcp.json` in the Cursor copy only: the plugin root',
  `becomes \`~/.cursor/plugins/local/<name>\`, the data directory \`~/.cursor/agent-bundle/plugin-data/<name>\``,
  '(created by the installer), an omitted `cwd` becomes the plugin root, `./` commands resolve against',
  'it, and every stdio server gains `PLUGIN_ROOT` / `PLUGIN_DATA` in its environment. The bundle itself',
  `stays spec-conformant; the pre-expansion document is kept in \`${installReceiptFile}\` (\`cursorExpansion\`),`,
  'and `agent-bundle doctor --host cursor` verifies the expanded paths (`AB7325`). Nothing is changed for',
  'other Agent Plugins clients, which expand the placeholders themselves.',
  '',
  '### Reinstall after a same-version rebuild',
  '',
  `The installer records an install receipt (\`${installReceiptFile}\`) and replaces its owned files in`,
  'place when the same version was rebuilt with different content; runtime state (`state/`) is never',
  'touched. Pass `--replace` (alias `--force`) to replace a different installed version or to adopt a',
  'copy installed before receipts existed. Foreign directories are refused with a content-hash',
  'comparison. For Codex and other native clients, remove and re-add the plugin through the client',
  'when only content changed at the same version.',
  '',
];

const installMarkdown = (model: NormalizedPlugin, target: BuiltInTarget): string => {
  const sections = (() => {
    switch (target) {
      case 'claude':
        return claudeInstructions(model);
      case 'codex':
        return codexInstructions(model);
      case 'cursor':
        return cursorInstructions(model);
      case 'portable':
        return portableInstructions();
      case 'plugin':
        return [...claudeInstructions(model), ...codexInstructions(model), ...cursorInstructions(model)];
      default: {
        const exhaustive: never = target;
        throw new TypeError(`Unknown built-in install target ${String(exhaustive)}.`);
      }
    }
  })();
  return [...header(model), ...sections].join('\n');
};

/**
 * The standalone Cursor safe-copy installer. It carries no imports from
 * agent-bundle, so it mirrors the receipt policy of `install/receipt.ts`
 * line for line: same receipt file and format, same owned-file hashing, same
 * ownership verdicts (receipt, legacy layout, foreign), and the same
 * owned-files-only in-place replacement. `tests/install-surface.test.ts` and
 * the host-install proofs pin the two implementations to each other.
 */
const cursorInstallerSource = (model: NormalizedPlugin): string => {
  const name = JSON.stringify(model.metadata.name);
  const version = JSON.stringify(model.metadata.version);
  return [
    '#!/usr/bin/env node',
    "import { execFile } from 'node:child_process';",
    "import { createHash, randomUUID } from 'node:crypto';",
    "import { cp, lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rename, rm, rmdir, writeFile } from 'node:fs/promises';",
    "import { homedir } from 'node:os';",
    "import { basename, dirname, join, relative, resolve, sep } from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    `const pluginName = ${name};`,
    `const pluginVersion = ${version};`,
    `const receiptFile = ${JSON.stringify(installReceiptFile)};`,
    `const receiptFormat = ${JSON.stringify(installReceiptFormat)};`,
    `const preservedEntries = ${JSON.stringify(preservedRuntimeEntries)};`,
    '// Runtime roots match case-insensitively: on case-insensitive filesystems State/ is state/.',
    'const isPreservedRoot = (name) => preservedEntries.includes(String(name).toLowerCase());',
    `const markerFiles = ${JSON.stringify(installSurfaceMarkerFiles)};`,
    "const source = resolve(fileURLToPath(new URL('.', import.meta.url)));",
    "const cursorRoot = join(homedir(), '.cursor');",
    "const installRoot = join(cursorRoot, 'plugins', 'local');",
    'const destination = join(installRoot, pluginName);',
    "const marketplaceRoot = join(cursorRoot, 'agent-bundle', 'marketplaces');",
    'const marketplaceRepo = join(marketplaceRoot, pluginName);',
    "const marketplacePlugin = join(marketplaceRepo, 'plugins', pluginName);",
    "// Agent Plugins 1.0.0 §9.1 PLUGIN_DATA for the Cursor copy: a writable, install-independent directory the installer creates.",
    "const pluginData = join(cursorRoot, 'agent-bundle', 'plugin-data', pluginName);",
    "const usage = 'Usage: node install.mjs [--mode local|marketplace] [--replace|--force] [--help]';",
    '',
    'let replace = false;',
    "let mode = 'local';",
    'const argv = process.argv.slice(2);',
    'for (let index = 0; index < argv.length; index += 1) {',
    '  const argument = argv[index];',
    "  if (argument === '--replace' || argument === '--force') { replace = true; continue; }",
    "  if (argument === '--mode') {",
    '    mode = argv[index + 1];',
    "    if (mode !== 'local' && mode !== 'marketplace') { console.error(`Install mode must be local or marketplace.\\n${usage}`); process.exit(2); }",
    '    index += 1;',
    '    continue;',
    '  }',
    "  if (argument === '--help' || argument === '-h') { console.log(usage); process.exit(0); }",
    '  console.error(`Unknown installer argument ${JSON.stringify(argument)}.\\n${usage}`);',
    '  process.exit(2);',
    '}',
    '',
    'const exists = async (path) => {',
    '  try { await lstat(path); return true; }',
    "  catch (error) { if (error?.code === 'ENOENT') return false; throw error; }",
    '};',
    "const unsupported = (relative) => new Error(`Refusing unsupported filesystem entry ${JSON.stringify(relative || '.')}.`);",
    "const toPosix = (path) => path.replaceAll('\\\\', '/');",
    'const short = (hash) => hash.slice(0, 12);',
    'const sortNames = (names) => [...names].sort((left, right) => left.localeCompare(right));',
    '// Every ancestor directory of the given POSIX-relative files, deduplicated and sorted.',
    'const directoriesOf = (files) => {',
    '  const directories = new Set();',
    '  for (const file of files) {',
    '    let directory = dirname(file);',
    "    while (directory !== '.' && directory !== '') { directories.add(directory); directory = dirname(directory); }",
    '  }',
    '  return sortNames(directories);',
    '};',
    '',
    '// path\\0mode\\0bytes\\0 per file; mode is x for an executable and - otherwise.',
    'const hashEntry = (hash, relative, metadata, bytes) => {',
    '  hash.update(toPosix(relative));',
    "  hash.update('\\0');",
    "  hash.update((metadata.mode & 0o111) === 0 ? '-' : 'x');",
    "  hash.update('\\0');",
    '  hash.update(bytes);',
    "  hash.update('\\0');",
    '};',
    '',
    '// Deterministic tree walk: symlinks and special files refused, the root receipt skipped. `transform`',
    '// maps a file\'s bytes to what the Cursor copy will hold (the Agent Plugins mcp.json expansion below), so',
    '// the artifact hash describes the installed form and reruns compare like for like.',
    'const inventory = async (root, transform) => {',
    '  const rootMetadata = await lstat(root);',
    "  if (rootMetadata.isSymbolicLink() || !rootMetadata.isDirectory()) throw unsupported('.');",
    "  const hash = createHash('sha256');",
    '  const files = [];',
    '  const visit = async (relative) => {',
    '    const absolute = join(root, relative);',
    '    const metadata = await lstat(absolute);',
    '    if (metadata.isSymbolicLink() || (!metadata.isDirectory() && !metadata.isFile())) throw unsupported(relative);',
    '    if (metadata.isDirectory()) {',
    '      for (const entry of (await readdir(absolute)).sort((left, right) => left.localeCompare(right))) await visit(join(relative, entry));',
    '      return;',
    '    }',
    '    // Every inventoried path must round-trip through a receipt unchanged (no backslash in a POSIX',
    '    // name, nothing the receipt reader rejects); refuse the rest up front.',
    '    const posixPath = toPosix(relative);',
    "    if ((sep === '/' && relative.includes('\\\\')) || !safeRelative(posixPath)) throw unsupported(sep === '/' ? relative : posixPath);",
    '    files.push(posixPath);',
    '    const bytes = await readFile(absolute);',
    '    hashEntry(hash, relative, metadata, transform === undefined ? bytes : transform(posixPath, bytes));',
    '  };',
    '  for (const entry of (await readdir(root)).sort((left, right) => left.localeCompare(right))) {',
    '    if (entry === receiptFile) {',
    '      // The receipt is deletion authority: skipped from the hash, must be a regular file.',
    '      if (!(await lstat(join(root, entry))).isFile()) throw unsupported(entry);',
    '      continue;',
    '    }',
    '    // Runtime-owned roots (state/) are never plugin content: not hashed, not installed, not owned.',
    '    if (isPreservedRoot(entry)) continue;',
    '    await visit(entry);',
    '  }',
    "  return { files, hash: hash.digest('hex') };",
    '};',
    '',
    'const treeHash = async (root) => (await inventory(root)).hash;',
    '',
    '// An existing entry is one of ours when its exact name is owned, or when the filesystem proves it a case',
    '// alias of an owned name (both spellings realpath to the same on-disk path). Inode equality is not used.',
    'const isOwnedEntry = async (root, owned, relative) => {',
    '  if (owned.has(relative)) return true;',
    '  const alias = relative.toLowerCase();',
    '  let canonical;',
    '  for (const candidate of owned) {',
    '    if (candidate.toLowerCase() !== alias) continue;',
    '    try {',
    '      canonical ??= await realpath(join(root, relative));',
    '      if ((await realpath(join(root, candidate))) === canonical) return true;',
    "    } catch (error) { if (error?.code !== 'ENOENT') throw error; }",
    '  }',
    '  return false;',
    '};',
    '',
    '// Every directory on the way to a listed path must be a real directory (no symlinked ancestors);',
    '// an owned regular file that a rebuild turns into a directory leaves as stale first, so it is tolerated.',
    'const assertRealAncestors = async (root, files, ownedFiles = new Set()) => {',
    '  const checked = new Set();',
    '  for (const file of files) {',
    '    let directory = dirname(file);',
    "    while (directory !== '.' && directory !== '') {",
    '      if (!checked.has(directory)) {',
    '        checked.add(directory);',
    '        try {',
    '          const metadata = await lstat(join(root, directory));',
    '          if (metadata.isSymbolicLink()) throw unsupported(directory);',
    '          if (!metadata.isDirectory() && !(metadata.isFile() && await isOwnedEntry(root, ownedFiles, directory))) {',
    '            throw unsupported(directory);',
    '          }',
    "        } catch (error) { if (error?.code !== 'ENOENT') throw error; }",
    '      }',
    '      directory = dirname(directory);',
    '    }',
    '  }',
    '};',
    '',
    '// Hashes exactly the owned files; a missing owned file simply changes the digest.',
    'const hashOwned = async (root, files) => {',
    '  await assertRealAncestors(root, files);',
    "  const hash = createHash('sha256');",
    '  for (const relative of files) {',
    '    const absolute = join(root, relative);',
    '    let metadata;',
    "    try { metadata = await lstat(absolute); } catch (error) { if (error?.code === 'ENOENT') continue; throw error; }",
    '    if (metadata.isSymbolicLink() || !metadata.isFile()) throw unsupported(relative);',
    '    hashEntry(hash, relative, metadata, await readFile(absolute));',
    '  }',
    "  return hash.digest('hex');",
    '};',
    '',
    '// Receipt paths drive deletions: POSIX-relative only, no backslashes, no empty/./.. segments, and no',
    '// segment Windows would normalise onto another entry (reserved characters, colons, trailing dot/space)',
    '// or resolve as a DOS device (NUL, CON.txt, COM1, LPT1.json, ...).',
    'const windowsDeviceName = /^(?:con|prn|aux|nul|com[0-9¹²³]|lpt[0-9¹²³])(?:\\.|$)/iu;',
    '// The receipt name is reserved as a top-level entry in every spelling, file or directory (a case alias',
    '// resolves to the receipt itself on case-insensitive filesystems).',
    "const safeRelative = (value) => typeof value === 'string' && value.length > 0 &&",
    "  value.split('/')[0].toLowerCase() !== receiptFile.toLowerCase() &&",
    "  !value.includes('\\\\') && !value.startsWith('/') && !isPreservedRoot(value.split('/')[0]) &&",
    "  value.split('/').every((segment) => segment !== '' && segment !== '.' && segment !== '..' &&",
    "    !/[<>:\"|?*]/u.test(segment) && !windowsDeviceName.test(segment) &&",
    '    [...segment].every((character) => character.charCodeAt(0) >= 0x20) &&',
    "    !segment.endsWith('.') && !segment.endsWith(' '));",
    '',
    'const readReceipt = async (root) => {',
    '  let value;',
    '  try {',
    '    if (!(await lstat(join(root, receiptFile))).isFile()) throw unsupported(receiptFile);',
    "    value = JSON.parse(await readFile(join(root, receiptFile), 'utf8'));",
    "  } catch (error) { if (error?.code === 'ENOENT' || error instanceof SyntaxError) return undefined; throw error; }",
    "  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined;",
    '  // Same shape check as the core reader: a receipt missing any field reads as absent.',
    "  if (value.format !== receiptFormat || typeof value.plugin !== 'string' || typeof value.version !== 'string' ||",
    "    typeof value.host !== 'string' || typeof value.contentHash !== 'string' || typeof value.installedAt !== 'string' ||",
    '    !Array.isArray(value.files) || !value.files.every(safeRelative) ||',
    '    !Array.isArray(value.directories) || !value.directories.every(safeRelative)) return undefined;',
    '  return value;',
    '};',
    '',
    'const readManifest = async (root) => {',
    "  for (const manifest of ['.cursor-plugin/plugin.json', 'plugin.json']) {",
    '    try {',
    "      const value = JSON.parse(await readFile(join(root, manifest), 'utf8'));",
    "      if (value !== null && typeof value === 'object' && typeof value.name === 'string') {",
    "        return { name: value.name, ...(typeof value.version === 'string' ? { version: value.version } : {}) };",
    '      }',
    "    } catch (error) { if (error?.code !== 'ENOENT' && !(error instanceof SyntaxError)) throw error; }",
    '  }',
    '  return undefined;',
    '};',
    '',
    'const hasMarkers = async (root) => {',
    '  for (const marker of markerFiles) if (!(await exists(join(root, marker)))) return false;',
    '  return true;',
    '};',
    '',
    '// Agent Plugins packs (root plugin.json with an agent-plugins.org $schema, no .cursor-plugin/plugin.json).',
    '// Observed on Cursor 3.18.25 (docs/audits/2026-09-03-agent-plugins-cursor-ide-proof.md): the loader spawns their',
    '// stdio servers without expanding ${PLUGIN_ROOT}/${PLUGIN_DATA} in args, env values or cwd, without providing',
    '// the reserved PLUGIN_ROOT/PLUGIN_DATA variables (spec 9.1), with an omitted cwd defaulting to the home directory',
    '// and with ./ commands resolved against the workspace folder (spec 7.2.1). The installer therefore expands those',
    '// forms itself in the Cursor copy of mcp.json and records the expansion in the receipt (provenance: derived).',
    "const agentPluginsSchemaPrefix = 'https://agent-plugins.org/schemas/';",
    'const isAgentPluginsPack = async (root) => {',
    "  if (await exists(join(root, '.cursor-plugin', 'plugin.json'))) return false;",
    '  try {',
    "    const manifest = JSON.parse(await readFile(join(root, 'plugin.json'), 'utf8'));",
    "    return manifest !== null && typeof manifest === 'object' && typeof manifest.$schema === 'string' && manifest.$schema.startsWith(agentPluginsSchemaPrefix);",
    "  } catch (error) { if (error?.code === 'ENOENT' || error?.code === 'EISDIR' || error instanceof SyntaxError) return false; throw error; }",
    '};',
    "const isRecord = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);",
    "const expandPlaceholders = (value) => value.replaceAll('${PLUGIN_ROOT}', destination).replaceAll('${PLUGIN_DATA}', pluginData);",
    '// A plugin-relative ./ path resolves against the plugin root (spec 7.2.1); anything else is expanded in place.',
    "const expandPath = (value) => value.startsWith('./') ? join(destination, value.slice(2)) : expandPlaceholders(value);",
    '// Every stdio server rewritten into the form Cursor launches; undefined when the document has none to expand',
    '// (skills-only or remote-only packs stay byte-identical to the bundle).',
    'const expandAgentPluginsMcp = (text) => {',
    '  let document;',
    '  try { document = JSON.parse(text); } catch { return undefined; }',
    '  if (!isRecord(document) || !isRecord(document.mcpServers)) return undefined;',
    '  let expanded = false;',
    '  const servers = {};',
    '  for (const [name, server] of Object.entries(document.mcpServers)) {',
    "    if (!isRecord(server) || server.type !== 'stdio' || typeof server.command !== 'string') { servers[name] = server; continue; }",
    '    expanded = true;',
    '    const env = {};',
    "    for (const [key, value] of Object.entries(isRecord(server.env) ? server.env : {})) env[key] = typeof value === 'string' ? expandPlaceholders(value) : value;",
    '    env.PLUGIN_ROOT = destination;',
    '    env.PLUGIN_DATA = pluginData;',
    '    servers[name] = {',
    '      ...server,',
    '      command: expandPath(server.command),',
    "      ...(Array.isArray(server.args) ? { args: server.args.map((argument) => typeof argument === 'string' ? expandPlaceholders(argument) : argument) } : {}),",
    "      cwd: typeof server.cwd === 'string' ? expandPath(server.cwd) : destination,",
    '      env,',
    '    };',
    '  }',
    '  if (!expanded) return undefined;',
    "  return `${JSON.stringify({ ...document, mcpServers: servers }, null, 2)}\\n`;",
    '};',
    'const agentPluginsPack = await isAgentPluginsPack(source);',
    'const expansion = await (async () => {',
    '  if (!agentPluginsPack) return undefined;',
    '  let text;',
    "  try { text = await readFile(join(source, 'mcp.json'), 'utf8'); }",
    "  catch (error) { if (error?.code === 'ENOENT' || error?.code === 'EISDIR') return undefined; throw error; }",
    '  const expanded = expandAgentPluginsMcp(text);',
    "  return expanded === undefined ? undefined : { documents: { 'mcp.json': text }, expanded, pluginData, pluginRoot: destination };",
    '})();',
    '// The Cursor copy differs from the bundle in exactly that one file; the artifact inventory hashes the expanded',
    '// form so receipts, no-op reruns and replacement compare the bundle with what the copy must hold.',
    "const cursorTransform = expansion === undefined ? undefined : (relativePath, bytes) => relativePath === 'mcp.json' ? Buffer.from(expansion.expanded, 'utf8') : bytes;",
    '',
    '// directories: the ones the installer created (all of them on a fresh install); only those are ever pruned.',
    'const receiptFor = (tree, directories = directoriesOf(tree.files)) => JSON.stringify({',
    '  contentHash: tree.hash,',
    '  // The pre-expansion document bytes and the values substituted, so Doctor validates the Agent Plugins',
    '  // contract against what the bundle shipped and proves the expansion against what Cursor spawns.',
    '  ...(expansion === undefined ? {} : { cursorExpansion: { documents: expansion.documents, pluginData: expansion.pluginData, pluginRoot: expansion.pluginRoot } }),',
    '  directories,',
    '  files: tree.files,',
    '  format: receiptFormat,',
    "  host: 'cursor',",
    '  installedAt: new Date().toISOString(),',
    '  plugin: pluginName,',
    '  version: pluginVersion,',
    "}, null, 2) + '\\n';",
    '',
    '// Staged sibling copy on the destination filesystem so every later rename is atomic.',
    'const stage = async (tree) => {',
    '  const parent = await mkdtemp(join(installRoot, `.${basename(destination)}.stage-`));',
    "  const root = join(parent, 'bundle');",
    '  try {',
    '    // Exactly the inventoried content is copied: runtime roots, a stray receipt, and empty directories',
    '    // (no plugin content: not hashed, not installed, not owned) never are.',
    '    const content = new Set([...tree.files, ...directoriesOf(tree.files)]);',
    '    const filter = (path) => {',
    '      const relativePath = relative(source, path);',
    "      return relativePath === '' || content.has(toPosix(relativePath));",
    '    };',
    '    await cp(source, root, { errorOnExist: true, filter, force: false, recursive: true, verbatimSymlinks: true });',
    "    if (expansion !== undefined) await writeFile(join(root, 'mcp.json'), expansion.expanded, 'utf8');",
    '    const staged = await inventory(root);',
    "    await writeFile(join(root, receiptFile), receiptFor(staged), 'utf8');",
    '    return { inventory: staged, parent, root };',
    '  } catch (error) {',
    '    await rm(parent, { force: true, recursive: true });',
    '    throw error;',
    '  }',
    '};',
    '',
    '// Prunes the now-empty ancestors of removed files, deepest first, but only installer-created ones:',
    '// a pre-existing directory that merely became an ancestor of an owned file is not ours to delete.',
    'const pruneEmptyDirectories = async (removed, ownedDirectories) => {',
    '  const pruned = new Set();',
    '  const candidates = directoriesOf(removed).filter((directory) => ownedDirectories.has(directory));',
    '  for (const directory of candidates.sort((left, right) => right.length - left.length)) {',
    '    try { await rmdir(join(destination, directory)); pruned.add(directory); }',
    "    catch (error) { if (!['ENOTEMPTY', 'ENOENT', 'EEXIST'].includes(error?.code)) throw error; }",
    '  }',
    '  return pruned;',
    '};',
    '// Creates missing ancestors one level at a time and records the ones this run created.',
    'const ensureAncestors = async (file, created) => {',
    '  const ancestors = [];',
    '  let directory = dirname(file);',
    "  while (directory !== '.' && directory !== '') { ancestors.unshift(directory); directory = dirname(directory); }",
    '  for (const ancestor of ancestors) {',
    '    if (created.has(ancestor)) continue;',
    '    try { await mkdir(join(destination, ancestor)); created.add(ancestor); }',
    "    catch (error) { if (error?.code !== 'EEXIST') throw error; }",
    '  }',
    '};',
    '',
    'if (!(await exists(cursorRoot)) || !(await lstat(cursorRoot)).isDirectory()) {',
    '  throw new Error(`Cursor is not installed in ${cursorRoot}.`);',
    '}',
    '',
    'const git = (cwd, args) => new Promise((resolvePromise, reject) => {',
    "  execFile('git', args, { cwd }, (error, stdout, stderr) => {",
    "    if (error?.code === 'ENOENT') {",
    "      reject(new Error('git is required for --mode marketplace; install git or use the default local mode.'));",
    '      return;',
    '    }',
    '    if (error) { reject(new Error(`git ${args[0]} failed: ${(stderr || stdout || error.message).trim()}`)); return; }',
    '    resolvePromise(stdout.trim());',
    '  });',
    '});',
    '',
    'const printMarketplaceSteps = (state, commit) => {',
    '  console.log(`${state} ${pluginName}@${pluginVersion} for cursor (marketplace mode) at ${marketplaceRepo}`);',
    "  console.log(`Marketplace: ${pluginName}-marketplace${commit ? ` @ ${commit}` : ''}`);",
    "  console.log('Next steps:');",
    '  console.log(`  1. Open Cursor, then Customize -> Plugins -> "Add Plugins from Local Repository" and select ${marketplaceRepo}.`);',
    '  console.log(`  2. Choose "${pluginName}" in the imported marketplace and select Install (user scope).`);',
    "  console.log('  3. Verify with `agent-bundle doctor --host cursor`: the plugin must appear under ~/.cursor/plugins/cache once Cursor has installed it.');",
    '};',
    '',
    "const marketplaceManifestPath = join(marketplaceRepo, '.cursor-plugin', 'marketplace.json');",
    '',
    "if (mode === 'marketplace' && !(await exists(join(source, '.cursor-plugin', 'plugin.json')))) {",
    "  throw new Error('--mode marketplace requires a Cursor Plugin (.cursor-plugin/plugin.json); Cursor marketplaces resolve plugins/<name>/.cursor-plugin/plugin.json. This bundle is an Agent Plugins (root plugin.json) pack: use the default local mode.');",
    '}',
    '// Owner and description come from the emitted .cursor-plugin/plugin.json, exactly as `agent-bundle install',
    '// cursor --mode marketplace` derives them, so both entry points stage byte-identical marketplace manifests.',
    'const marketplaceManifestFor = async () => {',
    "  const manifest = JSON.parse(await readFile(join(source, '.cursor-plugin', 'plugin.json'), 'utf8'));",
    "  const owner = typeof manifest?.author?.name === 'string' ? manifest.author.name : pluginName;",
    "  const description = typeof manifest?.description === 'string' ? { description: manifest.description } : {};",
    '  // Entry fields are limited to the pinned Cursor marketplace schema (name/source/description).',
    '  return `${JSON.stringify({',
    '    metadata: { description: `Agent Bundle local marketplace for ${pluginName}@${pluginVersion}.` },',
    '    name: `${pluginName}-marketplace`,',
    '    owner: { name: owner },',
    '    plugins: [{ ...description, name: pluginName, source: `plugins/${pluginName}` }],',
    '  }, null, 2)}\\n`;',
    '};',
    'const blobIndex = async (root, relative = \'\') => {',
    '  const index = new Map();',
    '  for (const name of await readdir(join(root, relative))) {',
    "    if (relative === '' && name === '.git') continue;",
    "    const child = relative === '' ? name : `${relative}/${name}`;",
    '    const metadata = await lstat(join(root, child));',
    '    if (metadata.isDirectory()) {',
    '      for (const [path, id] of await blobIndex(root, child)) index.set(path, id);',
    '    } else if (metadata.isFile()) {',
    '      const bytes = await readFile(join(root, child));',
    "      index.set(child, createHash('sha1').update(`blob ${bytes.length}\\0`).update(bytes).digest('hex'));",
    '    }',
    '  }',
    '  return index;',
    '};',
    'const findNestedGit = async (root, relative = \'\') => {',
    '  for (const name of (await readdir(join(root, relative))).sort()) {',
    "    const child = relative === '' ? name : join(relative, name);",
    "    if (name === '.git') return child;",
    '    const metadata = await lstat(join(root, child));',
    '    if (!metadata.isSymbolicLink() && metadata.isDirectory()) {',
    '      const nested = await findNestedGit(root, child);',
    '      if (nested !== undefined) return nested;',
    '    }',
    '  }',
    '  return undefined;',
    '};',
    "if (mode === 'marketplace') {",
    '  const marketplaceManifest = await marketplaceManifestFor();',
    '  const nestedGit = await findNestedGit(source);',
    '  if (nestedGit !== undefined) {',
    '    throw new Error(`--mode marketplace refuses bundle-internal Git metadata at ${JSON.stringify(nestedGit)}: git would record it as an empty gitlink and Cursor would import a plugin without files. Stage from a built bundle directory without .git, or use the default local mode.`);',
    '  }',
    '  await mkdir(marketplaceRoot, { recursive: true });',
    '  if (await exists(marketplaceRepo)) {',
    '    let stagedVersion;',
    "    try { stagedVersion = JSON.parse(await readFile(join(marketplacePlugin, '.cursor-plugin/plugin.json'), 'utf8')).version; }",
    "    catch (error) { if (error?.code !== 'ENOENT') throw error; }",
    '    if (stagedVersion !== undefined && stagedVersion !== pluginVersion) {',
    '      throw new Error(`Refusing version collision at ${marketplaceRepo}: found ${stagedVersion}, requested ${pluginVersion}.`);',
    '    }',
    "    if (await exists(marketplacePlugin) && await exists(join(marketplaceRepo, '.git')) && await treeHash(source) === await treeHash(marketplacePlugin)) {",
    '      let stagedManifest;',
    "      try { stagedManifest = await readFile(marketplaceManifestPath, 'utf8'); }",
    "      catch (error) { if (error?.code !== 'ENOENT') throw error; }",
    '      if (stagedManifest !== marketplaceManifest) {',
    '        throw new Error(`Refusing content collision at ${marketplaceRepo}: .cursor-plugin/marketplace.json differs from the generated marketplace manifest; remove the staged repository and rerun.`);',
    '      }',
    "      if (await git(marketplaceRepo, ['status', '--porcelain', '--untracked-files=all', '--ignored=matching']) !== '') {",
    '        throw new Error(`Refusing content collision at ${marketplaceRepo}: the working tree differs from the committed HEAD Cursor would import; remove the staged repository and rerun.`);',
    '      }',
    "      printMarketplaceSteps('Already staged', await git(marketplaceRepo, ['rev-parse', 'HEAD']));",
    '      process.exit(0);',
    '    }',
    '    throw new Error(`Refusing content collision at ${marketplaceRepo}.`);',
    '  }',
    '  const stageParent = await mkdtemp(join(marketplaceRoot, `.${pluginName}.stage-`));',
    "  const stage = join(stageParent, 'repo');",
    '  try {',
    "    await mkdir(join(stage, '.cursor-plugin'), { recursive: true });",
    "    await cp(source, join(stage, 'plugins', pluginName), { errorOnExist: true, force: false, recursive: true, verbatimSymlinks: true });",
    "    await writeFile(join(stage, '.cursor-plugin', 'marketplace.json'), marketplaceManifest);",
    "    await treeHash(join(stage, 'plugins', pluginName));",
    "    await git(stage, ['init', '-q', '--object-format=sha1']);",
    "    // Attributes (text/eol/filter/ident) would rewrite bytes in the index while leaving the tree clean; disable them.",
    "    await mkdir(join(stage, '.git', 'info'), { recursive: true });",
    "    await writeFile(join(stage, '.git', 'info', 'attributes'), '* -text -eol -filter -ident -working-tree-encoding -export-ignore -export-subst\\n');",
    "    await git(stage, ['-c', 'core.autocrlf=false', '-c', 'core.safecrlf=false', 'add', '--all', '--force']);",
    "    await git(stage, ['-c', 'user.name=agent-bundle', '-c', 'user.email=agent-bundle@localhost', '-c', 'commit.gpgsign=false', 'commit', '-q', '-m', `${pluginName}@${pluginVersion}`]);",
    '    // Prove the commit holds the staged bytes: every blob id must equal sha1("blob <len>\\0" + bytes).',
    '    const expected = await blobIndex(stage);',
    '    const committed = new Map();',
    "    for (const entry of (await git(stage, ['ls-tree', '-r', '-z', 'HEAD'])).split('\\0')) {",
    "      if (entry === '') continue;",
    "      const tab = entry.indexOf('\\t');",
    "      committed.set(entry.slice(tab + 1), entry.slice(0, tab).split(' ')[2]);",
    '    }',
    '    const drifted = [...expected].filter(([path, id]) => committed.get(path) !== id).map(([path]) => path);',
    '    const extra = [...committed.keys()].filter((path) => !expected.has(path));',
    '    if (drifted.length > 0 || extra.length > 0) {',
    '      throw new Error(`Cursor marketplace staging failed: the committed tree differs from the staged bundle bytes (${[...drifted, ...extra].map((path) => JSON.stringify(path)).join(\', \')}); a Git attribute or filter transformed them.`);',
    '    }',
    "    const commit = await git(stage, ['rev-parse', 'HEAD']);",
    '    await rename(stage, marketplaceRepo);',
    "    printMarketplaceSteps('Staged', commit);",
    '  } finally {',
    '    await rm(stageParent, { force: true, recursive: true });',
    '  }',
    '  process.exit(0);',
    '}',
    '',
    'await mkdir(installRoot, { recursive: true });',
    '// Spec 9.1: the data directory exists before any plugin subprocess is launched.',
    'if (expansion !== undefined) await mkdir(pluginData, { recursive: true });',
    'const artifact = await inventory(source, cursorTransform);',
    'const reportExpansion = () => {',
    '  if (expansion === undefined) return;',
    '  console.log(`Expanded Agent Plugins placeholders for Cursor in mcp.json: PLUGIN_ROOT=${destination} PLUGIN_DATA=${pluginData} (Cursor does not expand them; recorded in ${receiptFile})`);',
    '};',
    '',
    'if (!(await exists(destination))) {',
    '  const staged = await stage(artifact);',
    '  try {',
    '    await rename(staged.root, destination);',
    '    console.log(`Installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '    reportExpansion();',
    '  } finally {',
    '    await rm(staged.parent, { force: true, recursive: true });',
    '  }',
    '  process.exit(0);',
    '}',
    'if (source === destination) {',
    '  console.log(`Already installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '  process.exit(0);',
    '}',
    '',
    'const destinationMetadata = await lstat(destination);',
    "if (destinationMetadata.isSymbolicLink() || !destinationMetadata.isDirectory()) throw unsupported('.');",
    'const receipt = await readReceipt(destination);',
    'const manifest = await readManifest(destination);',
    'let ownership;',
    'let installedHash;',
    'if (receipt !== undefined && receipt.plugin === pluginName) {',
    "  ownership = 'receipt';",
    '  installedHash = await hashOwned(destination, receipt.files);',
    '} else {',
    '  installedHash = (await inventory(destination)).hash;',
    "  ownership = receipt === undefined && manifest?.name === pluginName && await hasMarkers(destination) ? 'legacy' : 'foreign';",
    '}',
    "const installedVersion = manifest?.version ?? (ownership === 'receipt' ? receipt.version : undefined);",
    "const installedName = manifest?.name ?? (ownership === 'receipt' ? receipt.plugin : pluginName);",
    'const sameContent = installedHash === artifact.hash;',
    'const verdict = installedVersion === undefined',
    "  ? (sameContent ? 'same content, installed version unknown' : 'different content, installed version unknown')",
    '  : installedVersion === pluginVersion',
    "    ? (sameContent ? 'same content' : 'same version, different content')",
    "    : (sameContent ? 'same content, different version' : 'different version');",
    "const detail = `installed ${installedName}@${installedVersion ?? 'unknown version'} content ${short(installedHash)} ` +",
    '  `vs artifact ${pluginName}@${pluginVersion} content ${short(artifact.hash)} (${verdict})`;',
    '// Foreign ownership wins over byte equality: a directory that is not ours is never current.',
    "if (ownership === 'foreign') {",
    '  throw new Error(`Refusing foreign install at ${destination}: ${detail}; the directory is not an agent-bundle install of ` +',
    '    `${pluginName}, so --replace does not apply. Remove it manually if it is stale.`);',
    '}',
    '// A receipt-managed copy is current only when its recorded inventory matches the artifact too.',
    "const inventoryMatches = ownership !== 'receipt' ||",
    '  (receipt.files.length === artifact.files.length && receipt.files.every((file, index) => file === artifact.files[index]));',
    'if (installedHash === artifact.hash && inventoryMatches) {',
    "  if (ownership === 'legacy' && replace) {",
    '    // Byte-identical pre-receipt copy: adoption only writes the receipt, through an exclusively',
    '    // created random sibling so no existing file or link is followed or overwritten.',
    '    const temporary = join(destination, `${receiptFile}.${randomUUID()}.tmp`);',
    "    const handle = await open(temporary, 'wx');",
    '    try {',
    "      await handle.writeFile(receiptFor(artifact, []), 'utf8'); // adoption created no directories",
    '      await handle.close();',
    '      await rename(temporary, join(destination, receiptFile));',
    '    } finally {',
    '      await rm(temporary, { force: true });',
    '    }',
    '    console.log(`Adopted ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '    reportExpansion();',
    '    process.exit(0);',
    '  }',
    '  console.log(`Already installed ${pluginName}@${pluginVersion} at ${destination} (content ${short(artifact.hash)})`);',
    '  process.exit(0);',
    '}',
    'if (installedVersion !== undefined && installedVersion !== pluginVersion && !replace) {',
    '  throw new Error(`Refusing version collision at ${destination}: ${detail}. Re-run with --replace to replace this agent-bundle install.`);',
    '}',
    "if (ownership === 'legacy' && !replace) {",
    '  throw new Error(`Refusing content collision at ${destination}: ${detail}; this copy predates install receipts. ` +',
    "    'Re-run with --replace once to adopt it; later same-version rebuilds replace automatically.');",
    '}',
    '',
    '// Owned-files-only replacement: stale owned files leave first, staged files rename over their',
    '// predecessors, and the receipt lands last as the commit marker. Unowned entries (runtime state) stay.',
    'const staged = await stage(artifact);',
    'try {',
    '  // A legacy copy has no inventory: only files the new artifact also ships count as owned; everything',
    '  // else (operator files, stale artifact files, runtime state) stays in place and remains unowned.',
    '  const incoming = new Set(staged.inventory.files);',
    '  let owned;',
    "  if (ownership === 'receipt') {",
    '    owned = receipt.files;',
    '  } else {',
    '    owned = [];',
    '    for (const file of (await inventory(destination)).files) {',
    '      if (await isOwnedEntry(destination, incoming, file)) owned.push(file);',
    '    }',
    '  }',
    '  const ownedSet = new Set(owned);',
    "  const ownedDirectories = new Set(ownership === 'receipt' ? receipt.directories : []);",
    '  await assertRealAncestors(destination, owned);',
    '  await assertRealAncestors(destination, staged.inventory.files, ownedSet);',
    '  // An existing directory at an incoming file path is fine only when it is wholly owned: it and every',
    '  // directory beneath were created by the installer, at least one file, every file owned, and no empty',
    '  // directory anywhere beneath (no evidence of ownership).',
    '  const isWhollyOwnedDirectory = async (relativePath) => {',
    '    let files = 0;',
    '    const visit = async (directory) => {',
    '      if (!(await isOwnedEntry(destination, ownedDirectories, directory))) return false;',
    '      const entries = (await readdir(join(destination, directory))).sort((left, right) => left.localeCompare(right));',
    '      if (entries.length === 0) return false;',
    '      for (const name of entries) {',
    '        const relative = `${directory}/${name}`;',
    '        const metadata = await lstat(join(destination, relative));',
    '        if (metadata.isSymbolicLink()) throw unsupported(relative);',
    '        if (metadata.isDirectory()) { if (!(await visit(relative))) return false; continue; }',
    '        if (!metadata.isFile() || !(await isOwnedEntry(destination, ownedSet, relative))) return false;',
    '        files += 1;',
    '      }',
    '      return true;',
    '    };',
    '    return (await visit(relativePath)) && files > 0;',
    '  };',
    '  const collisions = [];',
    '  for (const file of staged.inventory.files) {',
    '    if (ownedSet.has(file)) continue;',
    '    const target = join(destination, file);',
    '    let metadata;',
    "    try { metadata = await lstat(target); } catch (error) { if (error?.code === 'ENOENT' || error?.code === 'ENOTDIR') continue; throw error; }",
    '    const tolerated = metadata.isDirectory() && !metadata.isSymbolicLink()',
    '      ? await isWhollyOwnedDirectory(file)',
    '      : metadata.isFile() && await isOwnedEntry(destination, ownedSet, file);',
    '    if (!tolerated) collisions.push(file);',
    '  }',
    '  if (collisions.length > 0) {',
    "    throw new Error(`Refusing to overwrite unowned files at ${destination}: ${collisions.join(', ')}. Move them aside manually before replacing.`);",
    '  }',
    '  const stale = owned.filter((file) => !incoming.has(file));',
    '  for (const file of stale) await rm(join(destination, file), { force: true });',
    '  const pruned = await pruneEmptyDirectories(stale, ownedDirectories);',
    '  const created = new Set();',
    '  for (const file of staged.inventory.files) {',
    '    await ensureAncestors(file, created);',
    '    await rename(join(staged.root, file), join(destination, file));',
    '  }',
    '  // The receipt owns what the installer owns now: surviving directories it created before plus the',
    '  // ones this replacement created. Finalised in the private staging copy, then committed by rename.',
    '  const directories = sortNames(new Set([...[...ownedDirectories].filter((directory) => !pruned.has(directory)), ...created]));',
    "  await writeFile(join(staged.root, receiptFile), receiptFor(staged.inventory, directories), 'utf8');",
    '  await rename(join(staged.root, receiptFile), join(destination, receiptFile));',
    '  console.log(`Replaced ${pluginName}@${pluginVersion} at ${destination} (content ${short(installedHash)} -> ${short(artifact.hash)})`);',
    '  reportExpansion();',
    '} finally {',
    '  await rm(staged.parent, { force: true, recursive: true });',
    '}',
    '',
  ].join('\n');
};

const needsCursorInstaller = (target: BuiltInTarget): boolean =>
  target === 'cursor' || target === 'plugin' || target === 'portable';

export const installSurfaceRequirements = (
  target: string,
): readonly string[] => {
  if (target === 'cursor' || target === 'plugin' || target === 'portable') {
    return Object.freeze(['INSTALL.md', 'install.mjs']);
  }
  if (target === 'claude' || target === 'codex') {
    return Object.freeze(['INSTALL.md']);
  }
  return Object.freeze([]);
};

export const installSurfaceEntries = (
  model: NormalizedPlugin,
  target: BuiltInTarget,
): readonly TargetArtifactWrite[] => Object.freeze([
  Object.freeze({
    content: installMarkdown(model, target),
    kind: 'write' as const,
    relativePath: 'INSTALL.md',
    sourceInputs: sourceInputs(model.metadata.provenance.sourcePath),
  }),
  ...(needsCursorInstaller(target)
    ? [Object.freeze({
        content: cursorInstallerSource(model),
        kind: 'write' as const,
        relativePath: 'install.mjs',
        sourceInputs: sourceInputs(model.metadata.provenance.sourcePath),
      })]
    : []),
]);

export const withInstallSurface = (
  plan: TargetArtifactPlan,
  model: NormalizedPlugin,
  target: BuiltInTarget,
): TargetArtifactPlan => Object.freeze({
  ...plan,
  entries: sortedEntries([...plan.entries, ...installSurfaceEntries(model, target)]),
});
