import { randomUUID } from 'node:crypto';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative } from 'node:path';

import type { CompiledAgentRoute, CompiledRouteGraph } from './types.ts';

export const routeTypesRelativePath = '.agent-bundle/routes.d.ts';

const executableRoutes = (graph: CompiledRouteGraph): readonly CompiledAgentRoute[] => Object.freeze(
  [...new Map([
    ...graph.servers.flatMap((server) => server.routes.filter((route) => route.kind !== 'app')),
    ...(graph.cli?.routes ?? []),
    ...graph.events,
  ].map((route) => [route.id, route])).values()]
    .sort((left, right) => left.id.localeCompare(right.id)),
);

const declarationImport = (route: CompiledAgentRoute, index: number): string => {
  const relativePath = route.provenance.relativePath;
  const extension = extname(relativePath);
  const modulePath = `../${relativePath.slice(0, -extension.length)}.js`;
  return `import type * as route${String(index)} from ${JSON.stringify(modulePath)};`;
};

/** Deterministic declarations derived from the exact immutable graph used by packaging. */
export const generateRouteTypes = (graph: CompiledRouteGraph): string => {
  const routes = executableRoutes(graph);
  return [
    '// Generated by agent-bundle. Do not edit.',
    ...routes.map(declarationImport),
    '',
    'type SchemaOutput<Schema> = Schema extends { readonly _output: infer Output } ? Output : never;',
    'export type RouteContract<InputSchema, ResultSchema> = Readonly<{',
    '  input: SchemaOutput<InputSchema>;',
    '  result: SchemaOutput<ResultSchema>;',
    '}>;',
    'export type EventRouteContract<Component, Event extends string> = Readonly<{',
    '  component: Component;',
    '  event: Event;',
    '}>;',
    'type ComponentInput<Component> = Component extends (props: infer Props) => unknown ? Props : never;',
    'type ComponentResult<Component> = Component extends (...args: never[]) => infer Result ? Awaited<Result> : never;',
    'type ContractInput<Contract> =',
    '  Contract extends { readonly input: infer Input } ? Input',
    '    : Contract extends { readonly component: infer Component } ? ComponentInput<Component>',
    '      : never;',
    'type ContractResult<Contract> =',
    '  Contract extends { readonly result: infer Result } ? Result',
    '    : Contract extends { readonly component: infer Component } ? ComponentResult<Component>',
    '      : never;',
    '',
    'export interface AgentBundleRoutes {',
    ...routes.map((route, index) =>
      route.kind === 'event-route'
        ? `  ${JSON.stringify(route.id)}: EventRouteContract<typeof route${String(index)}.default, ${JSON.stringify(route.event)}>;`
        : `  ${JSON.stringify(route.id)}: RouteContract<typeof route${String(index)}.inputSchema, typeof route${String(index)}.resultSchema>;`),
    '}',
    '',
    'export type RouteId = keyof AgentBundleRoutes;',
    'export type RouteInput<Id extends RouteId> = ContractInput<AgentBundleRoutes[Id]>;',
    'export type RouteResult<Id extends RouteId> = ContractResult<AgentBundleRoutes[Id]>;',
    '',
  ].join('\n');
};

/**
 * Publishes typegen with a same-directory rename so dev readers observe the
 * previous complete file or the next complete file, never a partial write.
 */
export const writeRouteTypes = async (root: string, graph: CompiledRouteGraph): Promise<string> => {
  const output = join(root, routeTypesRelativePath);
  if (executableRoutes(graph).length === 0) {
    await rm(output, { force: true });
    return relative(root, output).replaceAll('\\', '/');
  }
  await mkdir(dirname(output), { recursive: true });
  const temporary = `${output}.${String(process.pid)}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, generateRouteTypes(graph), 'utf8');
    await rename(temporary, output);
  } finally {
    await rm(temporary, { force: true });
  }
  return relative(root, output).replaceAll('\\', '/');
};
