import { randomUUID } from 'node:crypto';
import { dirname, extname, join, relative } from 'node:path';

import { Effect, FileSystem } from 'effect';
import type { PlatformError } from 'effect/PlatformError';

import { ensuringRemoved, runWithPlatform } from '../effect/platform.ts';
import { providerKeyFromName } from './providers.ts';
import type { CompiledAgentRoute, CompiledProvider, CompiledRouteGraph } from './types.ts';

export const routeTypesRelativePath = '.agent-bundle/routes.d.ts';

const executableRoutes = (graph: CompiledRouteGraph): readonly CompiledAgentRoute[] => Object.freeze(
  [...new Map([
    ...graph.servers.flatMap((server) => server.routes.filter((route) => route.kind !== 'app')),
    ...(graph.cli?.routes ?? []),
    ...graph.events,
  ].map((route) => [route.id, route])).values()]
    .sort((left, right) => left.id.localeCompare(right.id)),
);

/** Providers in the exact order the generated request scopes execute them. */
const orderedProviders = (graph: CompiledRouteGraph): readonly CompiledProvider[] => Object.freeze(
  [...graph.providers].sort((left, right) => {
    const byKey = providerKeyFromName(left.name).localeCompare(providerKeyFromName(right.name));
    return byKey === 0 ? left.source.localeCompare(right.source) : byKey;
  }),
);

const declarationModulePath = (relativePath: string): string => {
  const extension = extname(relativePath);
  return `../${relativePath.slice(0, -extension.length)}.js`;
};

const declarationImport = (route: CompiledAgentRoute, index: number): string =>
  `import type * as route${String(index)} from ${JSON.stringify(declarationModulePath(route.provenance.relativePath))};`;

const providerImport = (provider: CompiledProvider, index: number): string =>
  `import type * as provider${String(index)} from ${JSON.stringify(declarationModulePath(provider.provenance.relativePath))};`;

const providerMember = (provider: CompiledProvider, index: number): string =>
  `  readonly ${JSON.stringify(providerKeyFromName(provider.name))}: ProviderValueOf<typeof provider${String(index)}.default>;`;

/**
 * The provider half of the generated declarations: `AgentBundleProviders`
 * maps each camel-cased key to its factory's awaited return type. Omitted for
 * provider-free graphs.
 */
const providerDeclarations = (providers: readonly CompiledProvider[]): readonly string[] =>
  providers.length === 0
    ? []
    : [
      'type ProviderValueOf<Factory> = Factory extends (...args: never[]) => infer Value ? Awaited<Value> : never;',
      '',
      'export interface AgentBundleProviders {',
      ...providers.map(providerMember),
      '}',
      '',
      'export type ProviderKey = keyof AgentBundleProviders;',
      'export type ProviderValue<Key extends ProviderKey> = AgentBundleProviders[Key];',
      '',
    ];

/**
 * The single `@agent-bundle/runtime` augmentation. Its `Register.routes`
 * member registers the thin `{ input, result }` contract map (TanStack
 * Router's `Register` pattern), so `agent-bundle/test`'s `renderRoute` narrows
 * its route-id parameter, `input`, and `result` from the project's own route
 * modules — a schema route's `inputSchema`/`resultSchema` output, an event
 * route's `{ canonical, native }` payload with no result; its
 * `AgentProviderValues` members make
 * `(await agent()).providers.<key>` observe each factory's resolved type.
 * Omitted for graphs with neither, so the augmentation never references a
 * module the project has no reason to depend on.
 */
const runtimeAugmentation = (
  routes: readonly CompiledAgentRoute[],
  providers: readonly CompiledProvider[],
): readonly string[] =>
  routes.length === 0 && providers.length === 0
    ? []
    : [
      "declare module '@agent-bundle/runtime' {",
      ...(routes.length === 0
        ? []
        : [
          '  interface Register {',
          '    readonly routes: AgentBundleRouteContracts;',
          '  }',
        ]),
      ...(providers.length === 0
        ? []
        : [
          '  interface AgentProviderValues {',
          ...providers.map(providerMember).map((line) => `  ${line}`),
          '  }',
        ]),
      '}',
      '',
    ];

/** Deterministic declarations derived from the exact immutable graph used by packaging. */
export const generateRouteTypes = (graph: CompiledRouteGraph): string => {
  const routes = executableRoutes(graph);
  const providers = orderedProviders(graph);
  return [
    '// Generated by agent-bundle. Do not edit.',
    ...routes.map(declarationImport),
    ...providers.map(providerImport),
    '',
    'type SchemaOutput<Schema> = Schema extends { readonly _output: infer Output } ? Output : never;',
    'export type RouteContract<InputSchema, ResultSchema> = Readonly<{',
    '  input: SchemaOutput<InputSchema>;',
    '  result: SchemaOutput<ResultSchema>;',
    '}>;',
    'export type EventRouteContract<Component, Event extends string> = Readonly<{',
    '  component: Component;',
    '  event: Event;',
    '}>;',
    'type ComponentInput<Component> = Component extends (props: infer Props) => unknown ? Props : never;',
    'type ComponentResult<Component> = Component extends (...args: never[]) => infer Result ? Awaited<Result> : never;',
    'type ContractInput<Contract> =',
    '  Contract extends { readonly input: infer Input } ? Input',
    '    : Contract extends { readonly component: infer Component } ? ComponentInput<Component>',
    '      : never;',
    'type ContractResult<Contract> =',
    '  Contract extends { readonly result: infer Result } ? Result',
    '    : Contract extends { readonly component: infer Component } ? ComponentResult<Component>',
    '      : never;',
    '// What the `agent-bundle/test` harness accepts and returns for one route: a schema route\'s own',
    '// input and result; for an event route the `{ canonical, native }` payload (the harness supplies',
    '// `signal` itself) and no result, since event modules export no `resultSchema`.',
    'type HarnessInput<Contract> =',
    '  Contract extends { readonly input: infer Input } ? Input',
    "    : Contract extends { readonly component: infer Component } ? Omit<ComponentInput<Component>, 'signal'>",
    '      : never;',
    'type HarnessResult<Contract> =',
    '  Contract extends { readonly result: infer Result } ? Result',
    '    : Contract extends { readonly component: unknown } ? undefined',
    '      : never;',
    '',
    'export interface AgentBundleRoutes {',
    ...routes.map((route, index) =>
      route.kind === 'event-route'
        ? `  ${JSON.stringify(route.id)}: EventRouteContract<typeof route${String(index)}.default, ${JSON.stringify(route.event)}>;`
        : `  ${JSON.stringify(route.id)}: RouteContract<typeof route${String(index)}.inputSchema, typeof route${String(index)}.resultSchema>;`),
    '}',
    '',
    'export type RouteId = keyof AgentBundleRoutes;',
    'export type RouteInput<Id extends RouteId> = ContractInput<AgentBundleRoutes[Id]>;',
    'export type RouteResult<Id extends RouteId> = ContractResult<AgentBundleRoutes[Id]>;',
    '/** The registered harness contract map: one `{ input, result }` per route id, for `@agent-bundle/runtime`\'s `Register`. */',
    'export type AgentBundleRouteContracts = {',
    '  readonly [Id in RouteId]: Readonly<{ input: HarnessInput<AgentBundleRoutes[Id]>; result: HarnessResult<AgentBundleRoutes[Id]> }>;',
    '};',
    '',
    ...providerDeclarations(providers),
    ...runtimeAugmentation(routes, providers),
  ].join('\n');
};

/**
 * Publishes typegen with a same-directory rename so dev readers observe the
 * previous complete file or the next complete file, never a partial write.
 * Runs on Effect `FileSystem` (the path arithmetic stays `node:path`: it is
 * string work shared with the pure generator above); a filesystem failure
 * still rejects with the same Node `ErrnoException`.
 */
export const writeRouteTypesProgram = (
  root: string,
  graph: CompiledRouteGraph,
): Effect.Effect<string, PlatformError, FileSystem.FileSystem> => Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const output = join(root, routeTypesRelativePath);
  const published = relative(root, output).replaceAll('\\', '/');
  if (executableRoutes(graph).length === 0 && graph.providers.length === 0) {
    yield* fs.remove(output, { force: true });
    return published;
  }
  yield* fs.makeDirectory(dirname(output), { recursive: true });
  const temporary = `${output}.${String(process.pid)}.${randomUUID()}.tmp`;
  yield* ensuringRemoved(temporary, Effect.gen(function* () {
    yield* fs.writeFileString(temporary, generateRouteTypes(graph));
    yield* fs.rename(temporary, output);
  }));
  return published;
});

export const writeRouteTypes = (root: string, graph: CompiledRouteGraph): Promise<string> =>
  runWithPlatform(writeRouteTypesProgram(root, graph));
