import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { describe, expect, it } from '@rstest/core';

import { generatedMetaModuleSource, metaModuleSpecifier, projectMeta } from '../src/build/meta.ts';
import { isDiagnostic } from '../src/core/diagnostics.ts';
import { ProjectService } from '../src/dev/project-service.ts';
import type { AgentBundleMeta } from '../src/meta.ts';
import {
  META_UNAVAILABLE_CODE,
  META_UNAVAILABLE_RECOVERY,
  MetaUnavailableError,
  metaUnavailableDiagnostic,
} from '../src/meta-diagnostic.ts';
import { agentBundleRstest } from '../src/rstest/index.ts';
import { metaModuleAliasKey, testMetaModuleSource } from '../src/rstest/meta-module.ts';
import { FALLBACK_PLUGIN_IDENTITY, isFallbackPluginIdentity, testManifestFromRouteGraph } from '../src/test/manifest.ts';
import { emptyCompiledRouteGraph } from '../src/routes/graph.ts';

const fixtureRoot = resolve(import.meta.dirname, '../fixtures/meta-consumer');
const metaModulePath = resolve(fixtureRoot, '.agent-bundle', 'test', 'meta.mjs');

type GeneratedMetaModule = AgentBundleMeta & { readonly default: AgentBundleMeta; readonly meta: AgentBundleMeta };

describe('agentBundleRstest aliases agent-bundle/meta (#386)', () => {
  it('routes the reserved specifier to a generated identity module under the project temp dir', async () => {
    const config = await agentBundleRstest({ root: fixtureRoot });

    expect(metaModuleAliasKey).toBe(`${metaModuleSpecifier}$`);
    expect(config.resolve).toEqual({ alias: { [metaModuleAliasKey]: metaModulePath } });
  });

  it('writes exactly the module the build injects, fed from the same package identity', async () => {
    await agentBundleRstest({ root: fixtureRoot });
    const written = await readFile(metaModulePath, 'utf8');

    // The build stamps `projectMeta(model.metadata)` from the same preparation.
    const prepared = await new ProjectService({ root: fixtureRoot }).prepare('inspect');
    expect(prepared.model).toBeDefined();
    const stamped = projectMeta(prepared.model!.metadata);
    expect(written).toBe(generatedMetaModuleSource(stamped));

    const packageJson = JSON.parse(await readFile(resolve(fixtureRoot, 'package.json'), 'utf8')) as {
      readonly name: string;
      readonly version: string;
    };
    expect(stamped).toEqual({
      name: 'meta-consumer',
      packageName: packageJson.name,
      packageVersion: packageJson.version,
      version: packageJson.version,
    });

    const loaded = await import(pathToFileURL(metaModulePath).href) as GeneratedMetaModule;
    expect({
      name: loaded.name,
      packageName: loaded.packageName,
      packageVersion: loaded.packageVersion,
      version: loaded.version,
    }).toEqual(stamped);
    expect(loaded.meta).toEqual(stamped);
    expect(loaded.default).toBe(loaded.meta);
    expect(Object.isFrozen(loaded.meta)).toBe(true);
  });

  it('never serves the model-less manifest placeholder as an identity', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-bundle-meta-no-model-'));
    try {
      // An empty root has no agent-bundle.config.ts, so preparation produces
      // no plugin model and the manifest carries the placeholder identity.
      const config = await agentBundleRstest({ root });
      const written = await readFile(config.resolve.alias[metaModuleAliasKey]!, 'utf8');

      expect(written).not.toContain('unknown');
      expect(written).not.toContain('0.0.0');
      expect(written).toContain('@generated by agent-bundle/rstest');

      let thrown: unknown;
      try {
        await import(pathToFileURL(config.resolve.alias[metaModuleAliasKey]!).href);
      } catch (error: unknown) {
        thrown = error;
      }
      const error = thrown as Error & { readonly code: string; readonly recovery: string };
      expect(error).toBeInstanceOf(Error);
      expect(error.name).toBe('AgentBundleMetaUnavailableError');
      expect(error.code).toBe('AB4760');
      expect(error.message).toContain('[AB4760] agent-bundle/meta is available only inside a surface Agent Bundle compiles');
      expect(error.message).toContain('produced no plugin model');
      expect(error.message).toContain(root);
      expect(error.recovery).toContain('Fix the compiler diagnostics');
      expect(error.message).not.toContain('ReferenceError');
    } finally {
      await rm(root, { force: true, recursive: true });
    }
  });

  it('recognizes the placeholder by reference and by value, and nothing else', () => {
    const placeholder = testManifestFromRouteGraph({ graph: emptyCompiledRouteGraph, projectRoot: '/tmp/none' });

    expect(placeholder.plugin).toBe(FALLBACK_PLUGIN_IDENTITY);
    expect(isFallbackPluginIdentity(placeholder.plugin)).toBe(true);
    expect(isFallbackPluginIdentity({ name: 'unknown', version: '0.0.0' })).toBe(true);
    expect(isFallbackPluginIdentity({ name: 'unknown', packageName: 'unknown', version: '0.0.0' })).toBe(false);
    expect(isFallbackPluginIdentity({ name: 'meta-consumer', version: '3.4.5' })).toBe(false);

    expect(testMetaModuleSource(placeholder)).toContain('throwUnavailable()');
    expect(testMetaModuleSource(placeholder)).not.toContain('export const name = "unknown"');
    expect(testMetaModuleSource({ ...placeholder, plugin: { name: 'meta-consumer', version: '3.4.5' } }))
      .toBe(generatedMetaModuleSource(projectMeta({ name: 'meta-consumer', version: '3.4.5' })));
  });
});

describe('the published agent-bundle/meta module outside the compiler', () => {
  it('rejects with the AB4760 diagnostic carrying the exact recovery', async () => {
    let thrown: unknown;
    try {
      await import('../src/meta.ts');
    } catch (error: unknown) {
      thrown = error;
    }

    expect(thrown).toBeInstanceOf(MetaUnavailableError);
    const error = thrown as MetaUnavailableError;
    expect(error.name).toBe('AgentBundleMetaUnavailableError');
    expect(error.code).toBe(META_UNAVAILABLE_CODE);
    expect(error.code).toBe('AB4760');
    expect(error.recovery).toBe(META_UNAVAILABLE_RECOVERY);
    expect(error.message).toContain('[AB4760] agent-bundle/meta is available only inside a surface Agent Bundle compiles');
    expect(error.message).toContain('recovery: Run the test under agentBundleRstest() or agentBundleBrowserRstest()');
    expect(error.message).toContain('alias `agent-bundle/meta`');
    expect(error.diagnostic).toEqual(metaUnavailableDiagnostic());
  });

  it('reports the diagnostic in the shared AB diagnostic shape', () => {
    const diagnostic = metaUnavailableDiagnostic();

    expect(isDiagnostic(diagnostic)).toBe(true);
    expect(diagnostic).toMatchObject({ code: 'AB4760', severity: 'error' });
    expect(diagnostic.recovery).toContain('agentBundleRstest()');
    expect(diagnostic.recovery).toContain('agent-bundle build');
    expect(diagnostic.recovery).toContain('.agent-bundle/test/meta.mjs');
    expect(Object.isFrozen(diagnostic)).toBe(true);
  });
});
